{445}{616}THE BLAIR WITCH PROJECT
{704}{767}In October of 1994,|three student filmmakers. . .
{771}{851}. . .disappeared in the woods near|Burkittsville, Maryland, . . .
{855}{898}. . .while shooting a documentary.
{906}{963}A year later|their footage was found.
{1098}{1151}-It's already recording. . .|-Okay.
{1181}{1201}This is my home. . .
{1205}{1274}-You look blurry. I'll zoom out.|-Okay.
{1293}{1317}Good morning.
{1322}{1361}-Got it?|-Okay, I got it.
{1367}{1399}This is my home, . . .
{1444}{1485}. . .which I am leaving for the weekend. . .
{1490}{1554}. . .to investigate the Blair Witch.
{1581}{1632}Essential reading: "How to Stay|Alive in the Woods", . . .
{1637}{1676}. . .'cause you never know what's|gonna happen.
{1681}{1720}And this is an important book. . .
{1726}{1804}. . . because it has the article about what|happened at Coffin Rock.
{1810}{1826}It looks pretty old. . .
{1830}{1885}It's totally old.|And this is my field notebook.
{1889}{1952}It's Mr. Punctuality.
{1981}{2030}How are you this morning?
{2040}{2056}Tired.
{2060}{2096}So I got the CP up.
{2101}{2117}Good.
{2147}{2208}That's what we're shooting on.
{2213}{2268}No one knows I took it,|but I got it.
{2274}{2333}Come into the house. Come on.
{2371}{2405}I can see you.
{2437}{2498}We're not gonna bump into shit,|I'm going backwards now.
{2504}{2549}We mustn't fuck up the cameras.
{2553}{2596}So where's Mikey?
{2600}{2643}-We have to go get him.|-Okay.
{2648}{2670}At 8:30.
{2675}{2695}Okay.
{2699}{2766}We're already behind schedule, but|it's important to have juice.
{2770}{2790}That's cool.
{2794}{2833}I guess you're Mike!
{2870}{2921}Wait. Stop.
{3012}{3067}Don't we get to meet your Mama?
{3169}{3210}See you later, Mom !
{3234}{3275}How are you, Mike?
{3279}{3307}I'm tired but I'm fine.
{3312}{3371}I'm real excited about this.|Thank you for the opportunity.
{3376}{3440}I'm very glad. Thanks for|getting the equipment together.
{3446}{3497}We've got enough|battery power to. . .
{3501}{3560}. .fuel a small country for a month.
{3566}{3646}We've got rice, fruit punch. . .
{3666}{3703}Oatmeal Raisin, baby.
{3711}{3756}The ultimate campfood.
{3808}{3846}Feel how soft.
{3926}{4000}-Marshmallows. . .|-Hey, you weasel. Out of my cart!
{4130}{4167}Do you believe in ghosts?
{4175}{4224}Ever heard of the Blair Witch?
{4287}{4384}Sounds familiar.|My sister went to Blair High School.
{4394}{4492}The woods around Halloween|are creepy.
{4496}{4580}-Can you tell me a little more?|-I don't wanna go cheesy.
{4585}{4656}I want to present|this straightforward.
{4660}{4713}The legend is unsettling.
{4720}{4756}Wanna get the. . .
{4781}{4834}. . .ceremonial first slate?
{4858}{4895}Absolutely.
{4943}{5023}The first slate for our|first shot.
{5044}{5126}Should we get our fingers open|and bleed on it?
{5136}{5170}A little blood-letting?
{5175}{5208}No, we'll save that for later.
{5213}{5256}Kiss the slate.
{5286}{5324}It's the first slate.
{5328}{5373}Marked by my lipstick.
{5377}{5440}Mikey, kiss it, good luck.
{5446}{5493}-There we go.|-Oh, he licked it. Bless him.
{5498}{5543}Don't eat it. We're gonna need it.
{5559}{5635}This is Burkittsville,|formerly Blair.
{5647}{5718}A small quiet Maryland town.
{5731}{5792}Like a small, quiet town anywhere.
{5797}{5906}Some 20 families laid roots here|over 200 years ago.
{5923}{5994}Many remain, either on this hill. . .
{6005}{6050}. . .or in the town below.
{6081}{6165}An unusually high number of|children are buried here. . .
{6175}{6230}. . . most of whom passed|in the 1 940's.
{6249}{6349}Yet no one here recalls anything|unusual about this time, . . .
{6357}{6400}. . . not to us, anyway.
{6408}{6455}Yet legend tells|A different story, . . .
{6461}{6516}. . .whose evidence is all around us.
{6533}{6572}Etched in stone.
{6735}{6821}We have shot the first scene,|the cemetery scene.
{6825}{6870}The opening is shot.
{6879}{6965}We're doing a documentary|about the Blair Witch.
{6990}{7084}-Have you heard of the Witch?|-That's an old, old story.
{7091}{7117}As I remember, . . .
{7122}{7196}. . . Mr. Parr was an old hermit, . . .
{7215}{7297}. . .and he lived up on a mountain.|He'd been there, . . .
{7301}{7334}. . . for a long, long, time.
{7338}{7391}-You heard of the Blair Witch?|-Several times.
{7397}{7450}What was the first incident?
{7454}{7542}I've heard stories about it|from people and neighbors,
{7547}{7623}I also saw a documentary on the|television. . .
{7629}{7707}. . .about her and legends|of Maryland, . . .
{7711}{7799}. . . my grandmother told us the story|to make us go to bed early.
{7803}{7885}They say if you stay up after dark|or walk around the house. . .
{7889}{7926}. . .the Blair witch will get you.
{7931}{8034}In the fall or winter of 1 940, . . .
{8039}{8113}. . .some young kids|started disappearing.
{8120}{8159}Nobody knew. . .
{8176}{8229}. . .why they were disappearing.
{8285}{8359}-A kind of an omen, isn't it?|-The creepiest story about her. . .
{8375}{8430}. . .was that two men out hunting. . .
{8433}{8521}. . .camped near the cabin|she's supposed to haunt. . .
{8527}{8543}No. No.
{8546}{8601}. . .and they just disappeared|forever.
{8619}{8691}I'm just telling a scary story,|but it's not true.
{8696}{8716}It's not true.
{8720}{8800}One day, old Mr. Parr|came into the market. . .
{8806}{8859}. . .and said "l'm finally finished".
{8863}{8887}And what did he mean by that?
{8892}{8931}Nobody knew at first. . .
{8936}{8983}But the police finally. . .
{8987}{9025}went up the mountain. . .
{9043}{9144}. . .and found the bodies of seven|kids in his house.
{9155}{9235}He would take the kids down|to the basement in twos. . .
{9239}{9294}. . .and he'd make one|face the corner. . .
{9318}{9361}. . .and he'd kill the other one. . .
{9373}{9447}. . .then he'd kill the one in|the corner too.
{9458}{9494}Those were the seven kids|that were missing
{9498}{9570}They brought the kids out of|the woods one at a time. . .
{9574}{9652}. . .it was terrible, it upset|the whole community.
{9657}{9702}He said he couldn't take|the eyes watching him. . .
{9708}{9800}. . .that's why he made them|face the corner like that.
{9804}{9849}All my life I've believed. . .
{9853}{9918}. . .in witches and ghosts and|that kind of stuff
{9921}{9966}Do you believe there are some|in this area?
{9971}{9987}Oh, definitely.
{9992}{10039}-Do you believe in witchcraft?|-No.
{10062}{10115}-Are you religious?|-Yep.
{10120}{10142}Alrighty.
{10146}{10246}Creepy stuff, but I think|something's happening with her.
{10250}{10307}And do you think she could|still be up there now?
{10313}{10354}-I don't go up there.|-You don't?
{10358}{10391}I believe enough not to go.
{10394}{10476}They say the woods are haunted|and stuff like that.
{10482}{10523}What? How are they haunted?
{10526}{10626}Well there's not many people|who say that it's haunted. . .
{10630}{10687}. . . but there was this old woman,|Mary Brown, who. . .
{10692}{10716}Mary Brown?
{10720}{10771}Yeah, and she was kind of crazy.
{10776}{10821}How was she seen by the community?
{10827}{10841}Crazy.
{10849}{10943}There's the American flag,|it's Mary's house.
{10961}{10987}I'm gonna bring her out.
{10992}{11043}You look for the best light, okay?
{11048}{11062}Okay.
{11130}{11191}This is Mary's gate.
{11224}{11281}I'm not even sure how to open it.
{11309}{11379}And something interesting|happened to you once. . .
{11383}{11434}You met the Blair witch?
{11455}{11473}Yes.
{11477}{11507}That is really. . .
{11515}{11572}. . . kind of a scary story.
{11596}{11628}To make ends meet. . .
{11632}{11671}. . . my Dad and I
{11677}{11730}. . . used to fish at Tappy's Creek.
{11738}{11807}In Burkittsville.
{11822}{11889}I was laying on the leaves. . .
{11906}{11978}. . .watching my pole, and|looking at the sky. . .
{11988}{12085}. . .and suddenly I felt|something near me. . .
{12097}{12140}. . . an eerie feeling. . .
{12158}{12205}. . . It was a woman. . .
{12219}{12274}. . .only on her|arms and hands. . .
{12278}{12323}. . .and everything. . .
{12328}{12365}. . .she had hair . . .
{12382}{12439}. . .dark, almost black hair. . .
{12455}{12491}. . .Iike a horse. . .
{12497}{12554}. . .Iike a fur, horse fur.
{12561}{12591}Then on her arm. . .
{12601}{12642}. . .she had a shawl. . .
{12661}{12710}And she scared you,|or threatened you?
{12730}{12812}She didn't say anything,|she just stared. . .
{12817}{12862}. . .and then she opened her shawl. . .
{12870}{12905}What was under there?
{12909}{12981}She had hair on her|body like a horse.
{12986}{13016}Hairy from head to toe?
{13021}{13078}Yeah. And her legs. . .
{13086}{13158}-How about her face?|-You could see she was a female.
{13175}{13232}She was just strange looking.
{13250}{13309}Thank God she's|not in the film business.
{13314}{13390}She thinks she is.|She also says she's a ballerina.
{13397}{13421}Get out.
{13426}{13469}And she says she's a historian. . .
{13473}{13493}I heard that.
{13497}{13552}. . .and that she's a scientist|at the Department of Energy.
{13557}{13633}I fucked up on Mary|with the depth of field.
{13638}{13704}You measured it in meters?|We're not in Europe.
{13718}{13767}The fucking lens|has meters on it.
{13773}{13830}It also has our system.
{13853}{13914}Nah, it has meters. Look.
{13964}{14009}But it's an American camera.
{14014}{14046}All those are meters.
{14055}{14094}What about the brown ones?
{14098}{14124}They're feet.
{14128}{14171}The brown ones are on there, right?
{14176}{14239}Yeah, but the white|ones are obvious.
{14242}{14334}-Didn't you use this camera before?|-Yeah. Once before.
{14343}{14386}How was today, guys?
{14417}{14456}I learned a lot, man.
{14460}{14503}About Mary Brown?
{14512}{14571}No, I learned a lot about. . .
{14589}{14615}1 6 mill?
{14625}{14686}. . .about shooting, just|shooting documentaries.
{14715}{14760}-We kicked some ass today.|-Cheers.
{14769}{14797}Very good day.
{14802}{14818}Excellent day.
{14823}{14853}Very good first day.
{14858}{14942}Let's do an equipment check,|after I call my mom.
{14947}{15021}-I got a bag of Utz and a beer.|-We don't need that on film.
{15029}{15072}So I guess you're covered then.
{15077}{15163}Could you run it a little|to check it's okay?
{15176}{15196}Sure.
{15205}{15293}I just want to check it's loaded|properly so we can shoot. . .
{15325}{15390}Okay, that's good, that's good.
{15397}{15446}That's good, thank you.
{15465}{15524}Let's relax, because we've got|a long day tomorrow.
{15530}{15583}Today's been easy.
{15588}{15651}We're gonna have to do a lot|of hiking, carry a lot of weight.
{15656}{15690}We're preparing.
{15694}{15772}Shut up, smartass.|Pour me a shot, please.
{15778}{15864}-I'm freaking out.|-You can't, you're the director.
{15869}{15961}I fucking have to do this now,|okay? Do we have any weed?
{15992}{16020}Here I go.
{16039}{16080}Drink! Drink!
{16148}{16195}I hate fucking scotch.
{16360}{16386}There's my friend Josh.
{16403}{16427}How are you?
{16431}{16453}I'm hurtin'.
{16458}{16503}I'm not ready for that thing yet.
{16511}{16548}I know you don't like it.
{16584}{16654}Hello. Welcome to day two.
{16661}{16714}The trail is along here.
{16720}{16779}It should be pretty obvious.
{16815}{16860}You guys heard of|the Blair witch?
{16867}{16933}I heard the myth. I don't|really believe much in it.
{16940}{16960}The myth?
{16963}{17004}That's all I think it is.
{17009}{17035}What'd you say, sir?
{17039}{17096}-I said damn fool kids never learn.|-Shut up.
{17103}{17138}Damn fool kids never learn?
{17142}{17160}That's what I said.
{17164}{17196}Why do you say that?
{17201}{17256}First of all, can I|have your permission. . .
{17261}{17327}. . .to use your image on a|video documentary?
{17337}{17384}I don't care about that, but. . .
{17391}{17432}You have to say yes or no, sir,
{17436}{17469}-Watch it.|-I'm sorry.
{17473}{17491}Yeah, sure, okay.
{17506}{17584}Some girl, in the late 1 800's. . .
{17596}{17651}. . . Robin Weaver, I|believe her name was, . . .
{17659}{17751}. . .supposedly wandered|off into the woods.
{17760}{17831}No "supposedly" about it.|She wandered off!
{17841}{17882}-Okay, wandered off.|-And got lost.
{17887}{17913}She got lost.
{17936}{17966}Wasn't no "supposedly".
{17986}{18020}Three days later. . .
{18025}{18103}. . .she appears back on her|grandmother's porch.
{18130}{18195}And everybody's mystified.
{18212}{18265}-She was babbling something. . .|-Her story.
{18270}{18323}Babbling something about. . .
{18329}{18390}. . .an old woman whose feet|never touched the ground.
{18435}{18523}I saw. . just by that|tree up the creek. . .
{18548}{18583}. . . about a hundred yards,
{18596}{18690}I saw a white misty thing.|Can't tell you what it was.
{18695}{18771}Like grey vapor rising|out of the trees.
{18776}{18810}Right out of the water.
{18815}{18837}Right out of the water?
{18842}{18899}Up the side of the trees,|Then it disappeared.
{18905}{18939}You're full of it.
{18943}{18994}I'm not. And I wasn't|drinking that day, either.
{19001}{19019}Sure you weren't.
{19024}{19071}How is that related to the|story of Coffin Rock?
{19076}{19137}It all ties in to the|story of Coffin Rock.
{19141}{19157}How's that?
{19191}{19265}Anybody round here. . .
{19270}{19342}. . . knows that the old woman has|haunted this area for years.
{19348}{19381}That's bullshit.
{19448}{19495}These woods are thick.
{19510}{19540}You excited?
{19565}{19587}You got it.
{19603}{19675}I hope he's not shooting a|whole shitload of stock.
{20220}{20263}I could help, but I'd|rather record.
{20268}{20286}Okay.
{20293}{20359}Packs on, we're ready to go.
{20363}{20408}We gotta go up to the shack?
{20413}{20431}Yeah.
{20594}{20653}My God, this is a very heavy pack.
{20738}{20785}Off to Coffin Rock.
{20789}{20836}I know exactly where we are now.
{20861}{20889}Mikey, give me the video camera.
{20894}{20947}I wanna get her going across, man.
{21039}{21086}I see a dirty behind.
{21186}{21210}Good jump.
{21216}{21230}Thank you.
{21232}{21275}There it is. See?
{21329}{21357}That's Coffin Rock.
{21469}{21526}"They went into the woods|ready to find death. . .
{21530}{21579}. . . but what they found|was inhumane. . .
{21584}{21653}. . .at the site called Coffin Rock.
{21663}{21720}. . . up on the rock, the torture. . .
{21735}{21805}. . .suffered by these five|brave men was obvious. . .
{21809}{21905}. . .they were tied up, one man's|hands tied to the next man's feet. . .
{21910}{21957}. . .forming a solid|human structure. . .
{21961}{22032}. . . blood indicated that|it had happened. . .
{22036}{22102}. . .while they were|alive and resisting. . .
{22108}{22190}. . .their intestines had been|crudely torn out. . .
{22198}{22292}. . .and on each of their faces there|was indecipherable writing. . .
{22296}{22347}. . .cut into their flesh|with precision. . .
{22354}{22418}. . .the men, shocked by|what had happened. . .
{22423}{22466}. . .went to find the sheriff. . .
{22471}{22551}. . .without sketching the writing|or touching the bodies . . .
{22555}{22604}. . .they returned to see|vultures at the rock.
{22609}{22703}But the bodies had been|removed by persons unknown. . .
{22708}{22779}. . .the stench of death|was still thick. . .
{22784}{22866}. . . but the bodies had been|taken in a matter of hours. . ."
{22896}{22978}That happened here|at Coffin Rock.
{23026}{23110}Let's rush, because I want|to camp, and it's 4:52.
{23115}{23185}It's late. We're gonna be|losing light soon.
{23222}{23302}But I can use the shot|without me in it. . .
{23311}{23407}. . . because I recorded sound|while reading the whole thing, . . .
{23420}{23473}. . . so I'm sure I can edit|it together somehow.
{23581}{23611}It's starting to rain.
{23628}{23652}Did you rent this thing?
{23658}{23746}Yeah. I don't have a|tent for three people.
{23758}{23784}Just wondering. . .
{23790}{23839}I don't usually travel with two men.
{23849}{23935}It is pouring with rain.|Can't even light a fire.
{23945}{23994}Show us what the stick is for.
{24037}{24115}Look. We've got our|very own leaning post.
{24127}{24195}If it smells of farts|too much in the night. . .
{24204}{24259}Okay, so I can't have a|cigarette in the tent, . . .
{24268}{24317}. . . but he can fart as|much as he wants?
{24322}{24410}No, I never gave Mike|a fart allowance.
{24430}{24468}You heard noises last night?
{24471}{24532}-I did.|-Problem is, I sleep like a log.
{24538}{24595}There were two separate noises. . .
{24601}{24670}. . .coming from two|areas over here. . .
{24690}{24735}. . .one of them could|have been an owl. . .
{24740}{24793}. . . but the other was a cackling.
{24825}{24851}No way.
{24856}{24894}It was a cackling, man.
{24900}{24957}If I heard a cackling,|I would've shit myself.
{24972}{25015}Where did we start yesterday?
{25022}{25058}Off the map.
{25076}{25168}I knew where we were going.|There was some confusion, but today. .
{25173}{25205}Wait, . . . say that again.
{25210}{25263}I said I knew where|we were going.
{25269}{25340}Wait, . . .was that a|full of shit statement?
{25344}{25360}No, it wasn't.
{25365}{25412}-So that wasn't bullshit?|-I knew where we were going.
{25416}{25469}You got us lost, man.
{25473}{25518}For a very short period of time.
{25531}{25570}Just don't get us lost today.
{25574}{25590}Yeah, seriously.
{25595}{25638}No. These places are|very well documented.
{25643}{25692}You happy with the documentary?
{25698}{25720}Yes, I am.
{25744}{25813}I'm very pleasantly surprised|by our little Mikey.
{25818}{25844}"Our Little Mikey?"
{25852}{25882}Our Little Mikey. . .
{25963}{26001}. . .a very spirited young man.
{26013}{26078}What do you think about the|witch? You think she exists?
{26087}{26126}I don't know.
{26190}{26245}Heather, I really hope|you find us a trail.
{26253}{26321}There's a trail up on|this hill. Don't worry.
{26378}{26423}We like shortcuts, don't we?
{26479}{26530}We like level shortcuts.
{26550}{26595}Not mountain shortcuts.
{26603}{26662}It's the first time we've|seen Mike's chest.
{26666}{26721}It's really hard to film on video.
{26733}{26794}He has really sporadic hair|patterns on his chest.
{26798}{26820}Like symbols.
{26824}{26885}It's like blank. . . hairy. .
{26894}{26935}. . . blank. . . hairy.
{26940}{26962}You should see my ass.
{26968}{27011}Look, here's fucking Uruguay.
{27050}{27091}-And there's Paraguay.|-Yeah.
{27098}{27131}I think I see Bolivia.
{27136}{27226}What killed this|mouse? Witchcraft?
{27283}{27315}How 'bout God?
{27344}{27383}Is that the Blair Witch?
{27393}{27498}No. I think it's Heather,|taking a piss.
{27525}{27599}You know, I|really have to go.
{27630}{27664}Ohhh. . . go!
{27691}{27775}We're near the cemetery|trail. It should only be . . .
{27782}{27825}-What?|-Says who?
{27830}{27854}Says me, of course.
{27882}{27968}We should be there|in about ninety minutes.
{28024}{28054}You guys cool with that?
{28074}{28090}What?
{28094}{28120}Ninety minutes?
{28127}{28188}-If you know where we're going.|-Sure.
{28195}{28240}Josh wants to look at the map now.
{28245}{28290}Though I know|where we're going.
{28295}{28350}If you'd known where|we were, we wouldn't be . . .
{28355}{28381}We're in the middle|of the fucking woods.
{28384}{28447}-How could you possibly know?|-Because some is offtrail.
{28451}{28515}What, somebody told you|there's a cemetery back there?
{28520}{28579}If we're lost, admit that, because. . .
{28585}{28613}. . . I know we're not lost.
{28618}{28673}You knew that yesterday, too,|and twice again today.
{28677}{28749}Bullshit! We have|not been lost today.
{28768}{28801}Not once.
{28808}{28830}Okay, this is where we were.
{28835}{28896}You said that it was|two miles away.
{28900}{28947}Then it's two hours away,|three hours away. . .
{28952}{29013}-Okay, just chill!|-Maybe it's four hours away.
{29017}{29085}-You agreed to do this project.|-I agreed to a scouted-out project.
{29089}{29157}-Not to wander round the woods.|-I told you that . . .
{29162}{29219}. . .getting to the locations|wasn't gonna be easy.
{29225}{29268}Mike, Mike. . .Okay, guys!
{29272}{29325}Please, you're being a smart-ass.
{29330}{29360}We're looking at the map. . .
{29365}{29426}. . .we'll find this the best we can.
{29432}{29522}This is where we were. We're|going more or less this way.
{29541}{29605}Okay, what do you say? Where|do you think we're going?
{29622}{29652}To tell you the truth. . .
{29754}{29822}. . .this is Greek|to me. It's useless.
{29826}{29846}Exactly.
{29852}{29889}So I'm putting my trust in you. . .
{29893}{29964}. . .that you know where it is.
{29984}{30006}Good.
{30036}{30097}Though I gotta tell you,|I don't fully trust you. . .
{30124}{30148}. . .and l. . .
{30165}{30189}What?
{30196}{30265}I don't know why you tape|every conversation, man.
{30269}{30295}Well, we're making a documentary.
{30301}{30375}Not about us getting lost,|it's about a witch !
{30408}{30441}I have a camera.
{30456}{30550}We'll all look back on this|and laugh, believe me.
{30563}{30610}Baby steps, man, baby steps.
{30615}{30693}Just breathe and don't look down.|No, you gotta look down.
{30697}{30731}Are you gonna have to crawl?
{30735}{30749}I'm gonna crawl.
{30753}{30767}Cool.
{30771}{30857}Think how cool the fucking|cemetery is gonna be.
{30909}{30976}Think of the joy of being|in a really good film.
{30981}{31001}Okay, shut the fuck up.
{31005}{31035}Okay, I'm quiet.
{31039}{31067}Shit. How am I gonna do this?
{31072}{31123}Okay. . . Mikey?
{31128}{31142}Yeah.
{31149}{31237}Dude, don't come across|with the DAT on your belly.
{31244}{31264}No way, man.
{31269}{31299}There's no chance.
{31310}{31353}How do we get it|across?
{31357}{31379}It's really fucking hard.
{31383}{31413}How we gonna get|it across?
{31417}{31497}The moss this morning was easy.|This stuff's slippery as shit.
{31519}{31560}Well, how do we get|the DAT across?
{31596}{31670}I don't know. Let|me put my pack down. . .
{31675}{31716}I'll just go back and forth, man.
{31721}{31770}Can you do it that way?
{31776}{31810}It's the only thing I can do.
{31815}{31849}Okay, we'll do it like that.
{31854}{31880}Oh, Christ!
{31885}{31930}Oh, what'd you drop?
{31936}{32026}Nothing.|The tree just broke.
{32031}{32057}Oh, fuck.
{32062}{32111}We're very, very close now.
{32174}{32211}You guys excited?
{32278}{32311}Okay.
{32327}{32360}What's this?
{32540}{32606}What's this? Dude, guys.
{32647}{32708}Remember what Mary|Brown said the other day?
{32750}{32815}What story from the|Bible was she telling us?
{32820}{32875}Fuck, I wasn't listening, I|thought she was crazy.
{32888}{32957}It was Esau, something about a|pile of rocks.
{32974}{33037}She was talking|about her rocks, man.
{33043}{33094}Well, what about|the rocks?
{33129}{33172}Anybody remember?
{33202}{33284}To live your life.
{33316}{33371}Looks like an lndian|burial ground, man.
{33377}{33424}I don't know if this counts,|three. . .
{33474}{33496}. . .four. . .
{33557}{33579}. . .five. . .
{33605}{33629}. . .six. . .
{33664}{33686}. . .seven.
{33692}{33733}Years ago witches|were roasted. . .
{33738}{33787}. . .just like my Vienna sausage.
{33802}{33871}Flames are licking you|like the Devil, Josh.
{33876}{33958}Sit back and hear a tale,|a tale of a fateful trip...
{33965}{34018}...that started on|this desert isle...
{34023}{34068}...aboard this tiny ship...
{34072}{34123}Yeah, but this ship|has a good captain. . .
{34127}{34184}. . . not a beer-guzzling|guy in a blue shirt.
{34192}{34228}He wasn't beer-guzzling.
{34241}{34290}They had no beer on|the island, man.
{34295}{34366}If they had beer, they'd|have had big-ass orgies.
{34400}{34476}You're like the Captain,|and Mike's your Gilligan.
{34488}{34525}-No offense.|-That's all right.
{34532}{34564}It was a compliment. . .
{34602}{34638}. . .Gilligan was a funny guy. . .
{34645}{34696}. . .the Captain was fat, though.
{34700}{34755}Well okay, let's call|it a thin Captain.
{34761}{34797}It's not Captain. . .
{34802}{34861}It's the Skipper.
{34902}{34930}No more Captain.
{34977}{35041}Here we are back at|the rock again. . .
{35045}{35086}. . .the cemetery deal.
{35129}{35180}I just wanna be careful|not to get in the shot.
{35387}{35426}It certainly is odd.
{35582}{35652}Please tell me you didn't|just knock that over.
{35658}{35695}I didn't just knock that over.
{35700}{35797}That's not very nice.|Let me put it back.
{35997}{36038}You can't be too careful.
{36048}{36081}What'd you think?
{36106}{36184}It was the same, only darker.
{36199}{36238}Yeah, pretty much.
{36268}{36329}All right. Bag it up.
{36348}{36372}Hello?
{36409}{36448}Shit, no light.
{36610}{36648}We were sleeping.
{36653}{36675}Do you want this?
{36702}{36747}Put it by the tent door.
{37082}{37110}Listen.
{37149}{37173}Hello?
{37214}{37238}Hello!
{37422}{37508}It's all around us.|Fucking weird.
{37524}{37569}Michael, aren't you|coming down?
{37579}{37605}I ain't going down there.
{37612}{37640}Why not?
{37645}{37686}-Because I don't hear shit.|-You're fucking scared.
{37690}{37718}Because I don't|hear anything!
{37723}{37776}You cannot deny hearing it.
{37801}{37846}Get your ass out! Come on !
{37903}{37952}This rain fucking blows, man.
{37958}{38005}I know. It's raining heavily.
{38020}{38104}Thanks mom for giving me|rain gear for my birthday.
{38110}{38148}God bless her.
{38154}{38201}What do you think it|was last night?
{38234}{38270}Personally?
{38273}{38287}Yeah.
{38291}{38344}Someone fucking|with your head.
{38349}{38392}But nobody knows|we're here.
{38397}{38456}Yeah, but. . .you ever see|"Deliverance"?
{38468}{38552}Well, whatever it was,|I just wanted to. . .
{38556}{38609}You were freaking out.|You bugged me out.
{38614}{38686}I was. I woke up suddenly|and shit's going down. . .
{38690}{38729}. . .and all I can think is|"l want it all. . .
{38734}{38799}I want it on sound,|I want it on sixteen.
{38803}{38869}If we see anything,|I want it on sixteen."
{38880}{38954}Sounded to me like a lot|of people running around. . .
{38959}{39006}. . . maybe they were locals|or whatever.
{39010}{39057}I don't know what|the hell they wanted.
{39062}{39159}We're deep in the woods, and|if people want to mess with us. . .
{39163}{39212}. . .then there's something|wrong with them. . .
{39217}{39251}. . .and I'm not gonna|get into that.
{39255}{39283}And if it wasn't people?
{39288}{39333}Well, I'm not gonna|get into that, either!
{39371}{39395}Fuck, man. .
{39443}{39486}. .it's been a very long day. . .
{39490}{39558}. . .a very wet, very long day.
{39630}{39712}Nobody's speaking to me|right now .
{39726}{39789}Dude, I don't remember|any of this.
{39810}{39838}What?
{39842}{39908}I don't remember any|of this coming from the car.
{39912}{40004}We have to go a different|route to get back. . .
{40010}{40059}. . . because we went|around in a curve.
{40118}{40171}Two more hours max, guys.
{40221}{40315}If we came by a short cut, why|are we going back a different way?
{40358}{40407}Because we have to go round. . .
{40422}{40481}It was the most direct way to|hit our two locations.
{40492}{40533}And this is the quickest|way back to the car.
{40538}{40560}Seriously?
{40565}{40599}Yes. Seriously.
{40603}{40672}-You know exactly what's going on?|-Yes. Let's just keep going.
{40677}{40703}All right.
{40724}{40779}Five minutes and we|do a map check.
{40790}{40816}All right.
{40834}{40926}We just did a map check,|and we're still on track.
{40946}{40982}That's not what I said.
{41002}{41057}We're all right. Come on,|just keep going.
{41143}{41194}Well the compass says. . .
{41200}{41253}. . .we go straight ahead,|that way.
{41270}{41321}We're in the middle of nowhere.
{41330}{41391}We've been in the middle|of nowhere for two days.
{41395}{41436}Just like the car.
{41440}{41504}Look at this shit, man !|This is nothing.
{41539}{41586}Let's just keep|going, all right?
{41658}{41693}I think we should camp.
{41697}{41723}Get the fuck out of here!
{41728}{41777}Why? 'Cause you don't know|where we are?
{41781}{41830}No, because we're still|A little way from the car. . .
{41835}{41867}. . .and it's gonna be dark soon.
{41901}{41981}-Look, I'm not sure. . .|-We don't camp. Stop the camera. . .
{41985}{42011}. . .and get us home.
{42015}{42097}Turn the camera off and give|me the fucking map.
{42103}{42137}Turn it off and get us home.
{42141}{42217}No, I'm filming. I want|to mark this occasion.
{42222}{42246}Give me the map.
{42251}{42321}The map is in my|pocket. Wait a second.
{42325}{42355}God damn !
{42366}{42446}If we keep our heads|together, we'll be just fine.
{42450}{42486}Fucking bullshit!
{42490}{42516}Mike, chill.
{42528}{42558}Just relax, Mike.
{42564}{42613}Don't fucking tell|me to relax!
{42626}{42700}Let's just sit down,|and check the map. . .
{42704}{42753}Yes. Let's do that, please.
{42786}{42818}Are you happy?
{42822}{42855}I'm not happy, no.
{42874}{42946}But the car isn't far. But we|can't find it in the dark.
{42951}{43017}Are you absolutely sure?
{43022}{43114}Yes. I'm so sorry. We can still|get the DAT back tomorrow.
{43117}{43147}We have to. . .
{43152}{43232}We will get the|DAT back on time.
{43237}{43271}And the camera.
{43275}{43310}We'll get it all|back tomorrow.
{43314}{43371}I start work tomorrow at nine.
{43376}{43400}I know.
{43404}{43453}It's fine. Let's go to sleep.
{43457}{43508}Let's just fucking camp, okay?
{43519}{43570}I wanna tape it from|inside the tent.
{43709}{43780}Whatever it is, it sounds the|same as last night.
{43958}{44026}Where's my boots? Fuck, it's cold. . .
{44145}{44167}Hello?
{44263}{44331}Shit, it's fucking freezing. . .
{44360}{44384}. . .there.
{44413}{44435}What?
{44440}{44466}I hear it.
{44481}{44515}I don't hear shit.
{44541}{44574}You hear that?
{44724}{44746}Shit. . .
{44995}{45021}Hello?
{45736}{45789}I think it's just a deer.
{45814}{45875}-Could be deer, I guess.|-It's just a deer.
{45881}{45918}I don't think so, man.
{45921}{45997}Sounds just like last night.|It's all around us.
{46002}{46032}It's gotta be just a deer.
{46037}{46070}It was a deer, man.
{46095}{46132}It wasn't like last night.
{46282}{46304}You say something?
{46308}{46394}Yes! Fucking listen ! Let's|get it on DAT. . . be quiet. . .
{46399}{46433}Okay, it's on.
{46523}{46589}Jesus Christ! What the|fuck was that?
{46758}{46807}It's not scared by our yelling.
{46928}{46969}Sounds like footsteps.
{46974}{47023}I know! It's a fucking person !
{47063}{47139}I don't see shit on video.|We'll just use DAT, right?
{47144}{47164}But I'm staying out.
{47168}{47201}You stay out here with me.
{47205}{47231}I am. I am.
{47239}{47333}What time is it? Anywhere|near morning?
{47356}{47372}Let me see. . .
{47377}{47438}Tell me it's five|O'clock or something.
{47474}{47492}Three.
{47496}{47516}Fuck!
{47552}{47628}Bullshit. This is|fucking crazy.
{47673}{47734}I'm sorry, Mike. We should|be home already.
{47739}{47788}This has got nothing to do. . .
{47814}{47857}. . .with what we're here for.
{47862}{47907}This is just it's bullshit.
{47930}{48001}Woke up this morning,|two seconds ago. . .
{48017}{48081}. . .and there are piles of|rocks outside our tent.
{48173}{48216}There are three, actually.
{48256}{48327}Are you positive those|weren't there last night?
{48332}{48401}I am fucking positive|they weren't here!
{48407}{48464}How could we have|just camped. . .
{48468}{48548}. . . between three piles of rocks|just by coincidence?
{48567}{48606}You don't think this is strange?
{48620}{48704}It is fucking weird, but|I really don't care. . .
{48709}{48770}. . . because all I want to do|is get to the goddam car.
{48775}{48849}Whatever it is,|man, right now. . .
{48858}{48901}. . .we have to get back to the car.
{48906}{48975}They obviously don't want us|Here, so let's get out.
{48986}{49039}We have to get the DAT back.
{49044}{49101}-That's what I mean.|-Okay, let's go.
{49105}{49175}Let's pack our shit up|and just walk.
{49187}{49209}Can we just walk?
{49214}{49236}Yes, we're out of here.
{49241}{49261}Okay, cool.
{49271}{49336}But we're leaving just|when it's all happening.
{49374}{49438}Put the fucking camera down.|Let's pack up the tent.
{49442}{49495}-Let's get out of the woods.|-Okay, hang on.
{49516}{49534}Come on !
{49538}{49610}No, I'm not scared!|I'm just tired and hungry. . .
{49614}{49690}I'm just fucking done, man.
{49695}{49717}All right.
{49788}{49818}Did you take it?
{49835}{49894}No, I didn't take the fucking map.
{49981}{50020}I'm not playing head games.
{50027}{50076}You're the one playing|head games.
{50081}{50115}But I'm not.
{50155}{50253}I don't have it. We have to go.|I'm serious, I don't have it.
{50258}{50282}Are you fucking serious?
{50286}{50335}Fucking serious. I don't have it.
{50373}{50414}Heather, that is not so cool, man.
{50419}{50460}I know it's not cool!
{50497}{50532}It's the fucking least|responsible thing. . .
{50542}{50595}. . .you could have done, man.
{50619}{50641}I know that.
{50696}{50735}You really don't have it?
{50781}{50820}One of you must have the map.
{50825}{50882}No, I don't have the map.|We gave it back to you. . .
{50889}{50936}. . .after map check yesterday.
{50956}{51011}I always keep it in the|same place. . .
{51016}{51063}. . .and if it's not there,|one of you must have it.
{51068}{51146}I did not get the goddam map|out of your fucking pants, man.
{51155}{51200}Well, I don't have it!
{51204}{51236}Look, why would I take it?
{51240}{51297}I just wanna get out|of here, man.
{51303}{51325}Me too.
{51332}{51350}Let's go!
{51354}{51436}No, you wanna stay and|film rocks, look around. . .
{51440}{51456}Let's go!
{51460}{51513}. .you wanna film this and that. . .|Which way?
{51517}{51533}That way.
{51538}{51581}We're in the|middle of the woods!
{51585}{51640}We can walk any way!
{51645}{51723}This way! Because we've|been going this way all day.
{51728}{51795}We're going this way!|We gotta find something!
{51809}{51848}I gave you back the map!
{51853}{51869}I gave you the map.
{51874}{51927}I gave you back the map!
{51954}{52009}-Let's just go.|-We can move as fast as we want. . .
{52014}{52081}. . . but there's no point if we have|no idea where we're going.
{52088}{52141}We're following the creek.|Mike seems happy with that.
{52145}{52175}Would you guys stop it?
{52362}{52415}We are fucked, we are done. . .
{52420}{52477}. . .we are dead, we are fucked.
{52569}{52668}I'm staying here. When you|find someone. . .
{52679}{52751}. . .tell them I'm under the|tree with the vine.
{52756}{52792}All blame aside. . .
{52863}{52902}. . .this is really fucked up.
{52906}{52963}I know.
{52978}{53033}We really need to work together.
{53038}{53089}-I realize that.|-Exactly. Exactly.
{53094}{53170}So we accept the fact that my|camera's not gonna be back. . .
{53174}{53204}. . .or your DAT.
{53211}{53272}No blame from now|on about that shit.
{53281}{53301}Look, seriously. . .
{53318}{53384}. . .this area's not that fucking big.
{53391}{53481}Exactly. It's very hard to get|lost in America these days. . .
{53488}{53558}. . .and even harder to stay lost.
{53566}{53584}What?
{53605}{53664}Well, we're doin' a pretty good|job of being lost.
{53674}{53760}If you're not home today,|and I'm not home today. . .
{53765}{53804}. . . people are gonna notice. . .
{53808}{53877}. . . My girlfriend's definitely|gonna notice. . .
{53889}{53955}. . .and she'll notice that|I haven't called.
{54006}{54074}. . .that I didn't get back and|I didn't call. . .
{54078}{54119}. . .so if by tonight we|haven't found shit. . .
{54123}{54188}. . .someone's gonna be looking for us.
{54192}{54214}Oh, no!
{54218}{54261}Not down here, go another way. . .
{54266}{54317}. . . I just got my whole shit wet.
{54401}{54473}Shit. Well, let's try it this way.
{54502}{54537}No, not this way. . .
{54565}{54616}. . . better try the other way.
{54672}{54746}-If we didn't have these packs. . .|-I don't mean to laugh. . .
{54769}{54801}Your feet are wet!
{54805}{54846}Is Michael laughing?
{54925}{54974}Shut up and cross the stream.
{54994}{55020}He's laughing. . .
{55024}{55095}. . .that's the first time|you've laughed in days.
{55202}{55274}I'm happy you|find it amusing. . .
{55279}{55334}. . .that I'll be uncomfortable|for the rest of the day.
{55353}{55404}Dude, uncomfort does not even. . .
{55431}{55459}Can we keep going, please?
{55468}{55519}No, we're gonna chill out!
{55561}{55635}-Didn't you want to get to the car?|-Oh boy! !
{55646}{55684}Okay, come on. . .Iet's get up here.
{55688}{55714}Oh shit.
{55738}{55804}You weren't lying to me about|the map, were you?
{55809}{55901}'Cause to me it seems like you're|having a little too much fun.
{55907}{55950}-Oh, Heather. .|-We're going a little stir crazy.
{55958}{56030}Heather! lf you make me|yell at this point. . .
{56040}{56079}. . .don't make me|yell at you, man.
{56085}{56169}Seriously, if you got the map, I|just wanna know you have it!
{56189}{56255}That would make me happy,|just to know you have it.
{56285}{56379}If I knew that, and I could see|it, I'd feel much better.
{56479}{56524}We're just trying to|be cool with you.
{56528}{56610}So I get laughed at 'cause|my shoes got wet.
{56616}{56648}It's fucking hilarious.
{56749}{56794}All our shoes are wet. . .
{56798}{56857}. . .we were laughing|at the situation.
{56863}{56879}Fine.
{56884}{56931}We're fucking hungry|and fucking tired. . .
{56935}{57002}-. . .what the hell else can we do?|-You know what?
{57006}{57065}I'm sorry, it's fucked up. . .
{57121}{57209}. . . but I kicked that map into the|creek yesterday.
{57221}{57309}It was useless and I kicked it|into the creek!
{57412}{57451}I fucking hope he's kidding.
{57487}{57507}Mike?
{57545}{57584}I really fucking hope he's kidding.
{57628}{57661}Mike, are you fucking kidding?
{57665}{57706}I'm sorry, man. I'm sorry.
{57711}{57793}You're kidding me. You have|gotta be fucking kidding me!
{57805}{57844}-You think it's a game?|-Get off me!
{57848}{57897}What the fuck?|Are you out of your mind?
{57902}{57959}No, I'm not. That map|wasn't doing shit!
{57964}{58042}Not for you, but I knew what|the fuck the map said! !
{58047}{58067}I'm sorry!
{58072}{58115}You're a fucking asshole!
{58121}{58141}I'm sorry.
{58146}{58178}You're a fucking asshole!
{58185}{58238}That map was useless!
{58243}{58310}If we get hurt or die here,|it's your fucking fault!
{58316}{58371}You understand?
{58431}{58490}How could you be|such an asshole?
{58519}{58601}-What were you thinking?|-You are fucking me up here!
{58608}{58677}I am not! That map|was useless!
{58698}{58732}It was useless to you !
{58749}{58814}Okay. . .
{58823}{58876}I didn't bring you out|here for this, man.
{58887}{58965}Sorry about the map, man.|What can I say?
{58972}{59066}-The map wasn't doing shit.|-Just don't say sorry.
{59072}{59107}It wasn't worth|shit to you.
{59111}{59182}I knew exactly where|we were!
{59186}{59255}Listen ! Yesterday I asked you what|fucking river we were on. . .
{59260}{59290}Shut up or else.
{59294}{59332}Turn the fucking camera off!
{59336}{59362}Give me the compass. . .
{59403}{59452}. . .you have betrayed us. . .
{59459}{59535}. . .way fucking beyond.|Give me the compass.
{59550}{59597}So have you for not getting|us out of the woods.
{59601}{59631}Yeah, thanks.
{59665}{59712}Can I have the fucking compass?
{59731}{59819}No. I bought the compass.|If you wanted one. . .
{59824}{59860}. . .you should've|bought your own.
{59865}{59908}You and he both fucked us up.
{59915}{59954}Why can't you admit that . . .
{59962}{60017}-. . .you fucked up from the start.|-Let's just walk south.
{60022}{60050}Because I haven't!
{60064}{60096}Why are we stopped?
{60227}{60253}Why are we stopped?
{60324}{60352}Just don't.
{60360}{60432}I'm just asking|Why we stopped.
{60483}{60542}Weren't we going south?
{60547}{60592}We all seemed very|Happy with that.
{60601}{60656}Why don't we carry on like that?
{60884}{60904}What?
{60911}{60960}There's all sorts of|Stuff down here!
{60965}{60995}What kind of stuff?
{61007}{61040}Voodoo shit!
{61084}{61114}What?
{61119}{61191}-Hanging all over the place!|-No way. . .
{61234}{61266}It's all over.
{61270}{61292}Holy shit. . .
{61344}{61403}Come up quick! I need the CP!
{61408}{61449}There's all sorts|Here, man !
{61472}{61529}This is fucking crazy shit.
{61608}{61649}Please, I gotta film this!
{61655}{61683}Take the fucking camera.
{61779}{61803}What the fuck is this?
{61808}{61838}I have no idea.
{62866}{62954}Jesus Christ, that's fucking creepy.
{63048}{63124}This is no redneck.|No redneck is this creative.
{63178}{63204}Can we go now?
{63208}{63242}Yeah, please.
{63261}{63320}Okay, I got everything on video.
{63325}{63391}Oh, Jesus Christ, I didn't|Even see these!
{63410}{63474}Okay, Heather, you got|Enough, man. Let's go.
{63482}{63564}-That's enough ! Stop taping!|-That's enough !
{63570}{63637}-Okay, we're going right now.|-Let's go!
{63643}{63731}Okay, we're out of here.|I'm leaving.
{63760}{63794}Come on, turn it off!
{63798}{63874}Help!
{63923}{63970}Please help us!
{64030}{64081}We won't get out of here like that.
{64088}{64110}Fuck!
{64129}{64159}Fuck!
{64177}{64259}I think I can say|that we're now lost.
{64282}{64319}I don't know what to do.
{64352}{64405}We should all get|lnside the tent.
{64413}{64435}All right.
{64442}{64489}Let's not light a fire tonight.
{64500}{64530}Yeah, that's my thinking.
{64535}{64611}-That's a good idea.|-We didn't light one the first night.
{64616}{64636}And nothing happened.
{64640}{64712}We light fires, and they know.|No one was following us.
{64722}{64756}We should turn that light off, too.
{64761}{64787}All right.
{64792}{64858}Seriously, anything|could attract them.
{64895}{64927}Let's just go to sleep.
{65270}{65300}Oh God.
{65411}{65443}Put this out.
{65983}{66059}Jesus Christ, little kids. Oh, God!
{66066}{66100}I'm gonna put my jeans on.
{66104}{66173}Take the video camera.|No, the DAT.
{66189}{66236}I'm gonna get this on video.
{66241}{66280}Oh, dear God, dear God!
{66590}{66626}Go, fucking go!
{66653}{66673}Oh God!
{66702}{66732}Oh God!
{66790}{66814}Hurry up!
{66819}{66888}I'm coming! My boots aren't laced!
{66915}{66962}Oh my God, what the fuck is that?
{66985}{67024}What the fuck is that?
{67203}{67229}Oh, shit!
{67410}{67465}Mike, where are you , man?
{67694}{67730}Turn the lights off. . .
{67745}{67802}. . .turn that light off.|turn it off, Josh.
{67867}{67945}All lights off,|all lights off.
{68122}{68152}I'm soaking.
{68154}{68182}That's okay.
{68196}{68226}What was that?
{68247}{68298}What the fuck is going on?
{68440}{68497}You hear that baby screaming?
{68504}{68563}Shut the fuck up. There's|no fucking baby.
{68569}{68639}-Yes there was.|-There was no fucking baby.
{68724}{68779}I haven't heard anything|since we ran away. . .
{68847}{68882}Oh my God, it's cold.
{68912}{68955}We should be quiet, okay?
{69185}{69248}I don't hear anything anymore.|Let's go back.
{69325}{69366}How long have we been here?
{69373}{69412}I don't know, man, an hour. . .?
{69464}{69515}The sun's up. We're okay now.
{69567}{69616}Let's just get back,|pack up, and go.
{69620}{69650}Okay.
{69716}{69759}What the fuck, man?
{69774}{69810}Where's my pack?
{69814}{69859}Right there. Where's mine?
{69871}{69910}What the fuck, man?
{70092}{70137}Why're they fucking|with us like this?
{70159}{70196}They just opened it up.
{70205}{70248}They spilled all my water!
{70256}{70293}Looks like slime, man.
{70314}{70342}It's just water, man.
{70358}{70415}It is slime. What the fuck is it?
{70425}{70460}Let's get out of here.
{70464}{70499}-Heather, turn that thing off!|-Let's go.
{70504}{70524}Okay.
{70529}{70576}I'm not interested|anymore! Let's go!
{70583}{70603}I know.
{70607}{70637}So turn it off.
{70651}{70712}Relax. Have we got everything here?
{70738}{70787}-Like I give a shit.|-Whose bag was opened?
{70792}{70820}It was mine!
{70898}{70930}Why you?
{70939}{70986}Are you not scared enough yet?
{70990}{71008}But why you?
{71021}{71064}Put it down. This is not funny.
{71069}{71128}Am I laughing at all?
{71135}{71211}No, but you're still doing|your documentary thing, man !
{71216}{71250}Still your fucking documentary!
{71256}{71322}-Don't touch it!|-Then turn the goddam thing off!
{71327}{71391}If you bite me again,|I'll throw you in river.
{71399}{71475}-Don't touch my camera.|-Turn it off!
{71482}{71502}I'm sorry.
{71506}{71542}I didn't mean it, okay?
{71546}{71568}You all right?
{71572}{71611}Yeah. I wanna go home. . .
{71616}{71661}. . . but I wanna get|what we can.
{71676}{71700}What the fuck. .?
{71755}{71789}Is this possible?
{71811}{71850}All right.
{71875}{71899}Here I go.
{71906}{71963}I hate crossing streams on logs.
{71981}{72020}If I never cross another stream. . .
{72026}{72092}. . .on a log, I'll die happy.
{72149}{72223}I see why you like the|video camera so much.
{72254}{72280}You do?
{72286}{72329}It's not quite reality.
{72396}{72441}Reality says we gotta move.
{72472}{72546}But it's a totally filtered|reality, man.
{72583}{72667}As if everything's|not quite the way it is.
{72746}{72783}Just leave him alone awhile
{72789}{72815}We need to go.
{72820}{72854}Leave him for five minutes.
{72876}{72945}Leave him alone. Five minutes.
{72955}{72991}Come on, he's lost it.
{73021}{73078}I know, but we've all|nearly lost it.
{73083}{73155}I know, but we got|to look after each other.
{73163}{73210}And we're not looking after him. . .
{73214}{73263}. . .if we film him|while he's crying.
{73268}{73286}I know.
{73290}{73323}I know you know.
{73326}{73387}Let's try and keep our wits.
{73392}{73424}But we have to go.
{73428}{73485}Sure. Believe me, I know.
{73489}{73530}It's hard to stay calm.
{73534}{73585}-We need to get out.|-I know.
{73590}{73625}You're not telling me|anything new,
{73644}{73693}Just let him calm down.
{73698}{73731}Anybody got a cigarette?
{73735}{73755}No, man.
{73760}{73792}No, there's none left.
{73812}{73859}Nobody has any cigarettes?
{73863}{73889}We're out.
{73962}{74005}Why the fuck. . .
{74012}{74077}. . .was this blue jelly|shit on my shit?
{74083}{74109}Let's go.
{74128}{74154}Let's go.
{74171}{74232}If we keep going south,|we'll get out.
{74259}{74283}Please. . .
{74319}{74382}I don't wanna camp|another fucking night.
{74387}{74444}Josh, none of us do.
{74449}{74471}I know you don't.
{74476}{74554}Whoever it is, is gonna come|back, and that's a fact.
{74561}{74587}It's not a fact.
{74593}{74663}It came three nights running,|and it's worse every night.
{74667}{74730}Just what I need to|hear right now.
{74734}{74818}I'm just trying to|rationally say that. . .
{74832}{74931}. . .with our walking speed,|they might just go on forever. .
{74951}{75033}Not possible in this country.
{75050}{75072}Why not?
{75076}{75164}Because we've destroyed most|of our woods in America.
{75168}{75248}-Let's just keep going.|-America, America...
{75257}{75339}... God shed your grace on thee...
{75413}{75509}... Once so proudly we hailed...
{75531}{75611}...at twilight's last gleaming...
{75669}{75708}That's the tree we crossed.
{75713}{75762}That tree is down. Same one.
{75826}{75861}Oh God!
{75881}{75899}Oh no. . .
{75903}{75968}You got to be kidding,|this is a joke!
{76006}{76055}It's not funny!
{76070}{76154}Mike, please stop. . .|please stop. . .
{76249}{76284}Oh no!
{76302}{76349}No, Mike, it's not the same log!
{76417}{76462}-Same log!|-Look, it's not!
{76466}{76511}Yes it is! Open your eyes!
{76517}{76564}It's not the same log. . .
{77004}{77041}It's the same log.
{77058}{77117}Fuck you, God! !
{77131}{77180}It's the same log.
{77355}{77419}Okay, it's okay.
{77555}{77608}Where do you wanna camp?
{77614}{77677}Going south didn't work.|Tomorrow we go east.
{77682}{77731}I don't know what to say, Josh.
{77760}{77821}How the fuck did we wind|up in the same place?
{77826}{77923}We walked south|all fucking day!
{77928}{77977}I don't know how we|ended up here!
{78142}{78199}Do you expect me to do,|or say something?
{78421}{78455}What do you wanna do?
{78608}{78638}Josh?
{78754}{78803}I wanna make movies, Heather.
{78868}{78909}Isn't that why we came?
{78961}{79004}Let's make some movies.
{79012}{79047}Fuck you.
{79113}{79149}Fuck you.
{79153}{79204}Let's not fight, please?
{79232}{79298}. . . I can't take it.|I can't fight.
{79303}{79395}We're screwed, and that's it.|Please stop fighting.
{79420}{79459}I'll do the first watch.
{79508}{79549}I got first watch.
{79745}{79790}It's not the time or place, guys.
{79795}{79838}We have things to prepare for.
{79842}{79883}Okay, here's your motivation. . .
{79890}{79968}. . .you're lost, you're angry and|no one's here to help you. . .
{79975}{80055}. . .there's a fucking witch who|keeps leaving shit around. . .
{80059}{80094}. . . no one can help you. . .
{80099}{80158}. . .she left little trinkets, and|you fucking took one. . .
{80164}{80225}. . .she's chasing us. And|no one can help you !
{80229}{80272}We walked fifteen hours today. . .
{80276}{80329}. . .and we ended up in the same place!
{80334}{80416}There's no one to help you !|That's your motivation !
{80511}{80544}Please stop.
{80548}{80630}Josh, quit it. She's had enough.
{80653}{80706}You got her back. Good one.
{80710}{80771}No, she's still making movies!
{80776}{80823}-Please stop.|-Still making movies.
{80828}{80897}It's all I have left, okay?|Just please stop.
{80958}{81023}Please stop yelling at me.
{81151}{81210}I'm fucking tired of|crying all day.
{81230}{81304}We gotta think like human beings.|We got things to do.
{81309}{81372}We've gotta do shifts.|We got lots to do.
{81519}{81576}You gonna write us a|happy ending, Heather?
{81793}{81832}Come on, turn it off.
{81855}{81902}You're getting like she was.
{82033}{82119}I don't know how you can|sew at this point, man,
{82123}{82168}Well, I'm cold.
{82182}{82229}-I know.|-I hear you.
{82236}{82293}The smallest comforts|we can get are good.
{82298}{82361}Doesn't it seem absurd,|though, at this point?
{82366}{82392}Yes, it does.
{82396}{82451}Lots of things seem absurd.
{82458}{82542}Like sleeping where we were|last night is freaking. . .
{82546}{82599}It's just fucking me up, period.
{82620}{82700}Really fucking me up, man.
{82795}{82869}-I'm sorry, man.|-Me too. It's all right.
{82876}{82913}I'm sorry, Heather.
{82925}{82955}It's all right.
{82966}{83017}Who wants a cheeseburger?
{83033}{83065}I do, I do. . .
{83087}{83144}I got a cheeseburger in my pocket.
{83150}{83234}Do you? Can I have a|light to cut this?
{83252}{83289}Know what I'd fucking love?
{83299}{83321}What?
{83326}{83358}Mashed potatoes.
{83387}{83415}Me too.
{83469}{83538}My mom's mashed potatoes.
{83639}{83696}You'll have them again very soon.
{83732}{83808}Mashed potatoes|and a piece of ass.
{83849}{83875}Josh?
{83967}{84030}Fuck, we never go out of earshot!
{84060}{84103}Come on, calm down.
{84138}{84173}How can l?
{84404}{84440}He's probably at the river.
{84444}{84501}If he was there,|he could hear me.
{84618}{84659}Wait for him to respond.
{84677}{84726}Remember what he said yesterday?
{84735}{84761}What?
{84802}{84880}About the shit on his bag.
{84978}{85068}Let's go. We've gotta find|him. Come on.
{85075}{85165}If we can't even find the car,|how are we gonna find Josh?
{85170}{85194}Come on.
{85200}{85239}No, I'm fine.
{85265}{85310}Come on, come on, relax.
{85315}{85376}All right, let's take|Down the tent. . .
{85389}{85422}. . .and when he's back, we'll go.
{85430}{85473}I'm losing my mind, Mike.
{85486}{85518}Josh hasn't come back.
{85522}{85540}Heather?
{85564}{85601}I'm here, Mike.
{85683}{85746}I don't know if Josh ran off.
{85782}{85818}All his shit's here.
{85865}{85895}I've got the camera. . .
{85923}{85982}. . . I don't know how I'm|gonna hike with the camera.
{85998}{86045}Sure you wanna take it?
{86049}{86077}We have to take the camera.
{86121}{86168}How do you feel about east?
{86216}{86254}How do you feel?
{86307}{86350}Well, south didn't work.
{86395}{86483}Which witch was worse, the one|from the east or from the south?
{86530}{86593}The witch of the|west was the bad one.
{86606}{86636}Let's go east.
{86725}{86755}What the hell is that?
{86792}{86814}Josh?
{86941}{86982}We'll have to put up the tent.
{87274}{87317}I'd like a meatball.
{87322}{87357}Just one meatball?
{87362}{87413}And a big glass of red wine.
{87417}{87491}Yeah, I would like a whole|fucking bottle of Bordeaux.
{87500}{87538}And a pack of smokes.
{87543}{87633}That'd be good.|and a long, hot bath.
{87637}{87673}And a big pumpkin pie.
{87678}{87721}A pumpkin pie with ice cream?
{87761}{87810}Warm with milky ice cream?
{87815}{87845}Yeah, sounds good.
{87856}{87913}What do you like|to do on a Sunday?
{87969}{88038}I used to like to drive to the|woods and go hiking.
{88130}{88173}But I think that might change now.
{88190}{88229}I think you could scratch that.
{88581}{88616}Should we open the door?
{88648}{88685}Is it a trick?
{88917}{88941}Josh !
{88986}{89012}Josh !
{89307}{89346}Where's it coming from?
{89690}{89761}Josh, where are you?|Tell me where you are!
{89852}{89923}Oh my God, no.
{90074}{90127}Do you think that's them again?
{90294}{90318}Is it over here?
{90323}{90364}No, it's over here.
{90620}{90650}We'll look for him.
{90963}{91043}I don't know if it's really him.
{91340}{91391}I don't even know where to look.
{91509}{91568}Tell me where you are, Josh !
{91645}{91665}Mike?
{91671}{91722}-What?|-Please don't fall asleep.
{91727}{91761}I can't fall asleep.
{91854}{91936}Whatever it is, it|knows Josh has gone.
{92069}{92140}If that was Josh, he would've|said where he was.
{92244}{92303}Whatever it was, it|sounded like Josh.
{92355}{92377}See?
{92404}{92471}I just want to show you|that Mike's here.
{92485}{92520}There. He's sleeping.
{92713}{92741}Oh, shit.
{92833}{92867}What the hell is that?
{92956}{92991}-Mike.|-What?
{93036}{93077}There's something out here.
{93235}{93309}Okay,
{93342}{93397}I'm gonna move it|from in front of the tent.
{93403}{93448}-Get rid of it.|-Okay.
{93500}{93578}I'm taking it away|from the tent.
{93601}{93652}I'm just throwing it.
{93789}{93855}We'll just keep walking, okay.
{93860}{93886}Okay.
{93979}{94075}I found some cigarettes|at the bottom of my pack. . .
{94079}{94143}. . .so if we're smoking,|we're still alive.
{95353}{95390}It's all full of blood.
{96352}{96436}Shit, shit, shit!
{96588}{96620}Oh my God!
{96949}{96981}Okay, see. . .?
{97015}{97037}Yeah?
{97080}{97102}What are you doing?
{97107}{97156}Just washing my hands!
{97163}{97179}What?
{97183}{97220}Just washing my hands!
{97243}{97267}I'm fine.
{97285}{97322}I'm gonna put my gloves on.
{97556}{97580}You all right?
{97584}{97676}I'm okay, I'm okay.
{97761}{97787}You need help?
{97791}{97842}No, I don't need any help.
{97871}{97897}I'm okay.
{97901}{97917}What happened?
{97921}{98001}Nothing. I'm just very|hungry and very tired. . .
{98017}{98066}. . .and very scared, and I just|wanna go home, okay?
{98071}{98089}Okay.
{98093}{98140}But I'm fine, and we're okay.
{98314}{98367}Ow! My hair's caught.
{98434}{98500}Thank you, thank you.
{98554}{98636}Okay, okay.
{99681}{99745}Two thousand one|hundred thirty games. . .
{99763}{99824}. . .one more season and|Cal Ripken is king!
{99942}{99981}And I won't see it. . .
{100008}{100059}. . . because I'll be in the woods.
{100426}{100506}Tell me you're not|eating a dry leaf.
{100773}{100812}I just want to apologize. . .
{100851}{100892}. . .to Mike's mom. . .
{100918}{100959}. . .and Josh's mom. . .
{100984}{101023}. . .and my mom. . .
{101097}{101154}. . .and I'm sorry to everyone. . .
{101211}{101258}. . . I was very naïve.
{101364}{101454}I am so, so, sorry. . .
{101476}{101525}. . .for everything that's happened. . .
{101562}{101626}. . . because in spite of|what Mike says now. . .
{101630}{101660}. . .it was my fault. . .
{101701}{101742}. . . because it was my project. . .
{101767}{101806}. . .and I insisted. . .
{101847}{101890}. . .insisted on everything.
{101913}{101980}I insisted we weren't lost. . .
{102012}{102079}. . . I insisted we keep going. . .
{102096}{102160}. . . I insisted we walk south.
{102196}{102264}Everything had|to be my way.
{102272}{102325}And this is how we've ended up.
{102356}{102432}And it's all because of me|that we're here now. . .
{102440}{102497}. . . hungry and cold. . .
{102552}{102593}. . .and hunted.
{102717}{102758}I love you, mom. . .
{102786}{102816}. . .dad. . .
{102884}{102929}. . . I am so sorry.
{103076}{103114}. . .what was that?
{103421}{103476}I'm scared to close my eyes. . .
{103498}{103545}. . .and scared to open them.
{103719}{103752}Oh God. . .
{103768}{103811}. . .we're gonna die here.
{103916}{103971}-You got it?|-You ready?
{104015}{104054}Oh, Jesus Christ.
{104327}{104357}You ready?
{104361}{104408}Here, take this light.
{104455}{104520}That can't be him.
{105485}{105542}Holy shit, it's a house.
{105589}{105665}-Watch your step.|-Holy shit, Holy shit. . .
{106172}{106192}Josh?
{106536}{106604}Mike. Mike.
{106642}{106666}Come on.
{106692}{106731}Mike, where the fuck are you?
{106736}{106783}Come on, I'm in the house!
{106795}{106856}Mike, don't go in there, please!
{107306}{107392}Mike, please!|Mike, where are you?
{107397}{107423}I'm right here!
{107595}{107623}Where is he?
{107630}{107673}Mike, please don't.
{107893}{107925}Is he in here?
{107929}{107951}No.
{108299}{108329}Oh, Jesus.
{108335}{108363}Where is he?
{108397}{108436}Are you gonna go upstairs?
{108483}{108534}I hear him. I hear him.
{108546}{108591}I hear you. Josh !
{108793}{108834}I'm going upstairs.
{108918}{108994}Oh, God, oh.
{109110}{109132}Hear that?
{109182}{109208}Where is he?
{109218}{109257}Where are you?
{109311}{109339}Come on !
{109442}{109478}I'm getting downstairs.
{109508}{109569}Come on, I hear him, downstairs!
{109599}{109615}Mike!
{109619}{109641}Come on !
{109647}{109663}Mike!
{109667}{109687}Josh !
{109692}{109722}Wait!
{109852}{109926}Josh, is that you down there?
