{4549}{4636}Oh boy!|This global warming is killing me!
{4639}{4732}This|is too hot..the ice age was too cold..
{4745}{4806}What would it take to make you happy?
{4846}{4889}This.. I like!
{5930}{6000}No running Jane! Camp rules..
{6058}{6096}Make me, Sloth!
{6100}{6141}Make me...sir!
{6164}{6195}It’s all about respect...
{6273}{6318}Sarah. You just ate! Wait an hour!
{6319}{6381}Hector! No,no! You can't pee-pee there!
{6392}{6424}Ok,ok! there is fine..
{6427}{6470}Ashley! Stop picking your...
{6471}{6503}Pinata!
{6511}{6535}Stop!
{6541}{6588}...you're supposed to wear blindfolds!
{6591}{6621}Ok!
{6638}{6684}Hey, it's my turn to hit the sloth!
{6684}{6771}..mine..mine...mine....mine!
{6892}{6941}Hey! You didn't have any candy in you!
{6952}{6992}Let’s bury him!!
{7121}{7201}Hey, hey! Whoah..|Who said you kids can torture the sloth?
{7202}{7258}Manny, don't squash their creativity..
{7270}{7308}Hey Manny! Diego!!
{7309}{7356}My bad mammal jammel!
{7361}{7402}Wanna give a sloth a hand?
{7452}{7493}Look.. I opened my camp!
{7493}{7529}Come forth and sit...
{7532}{7562}It means camp of Sid!
{7565}{7639}Congratulations.|You’re now an idiot in two languages..
{7641}{7663}Shhhh...!
{7665}{7714}…not in front of the K-l-D-G!
{7715}{7775}These little guys love me! Right, Billy?
{7775}{7815}Don’t make me eat you!
{7833}{7899}Funny, kid!|That's why they're called kids!
{7909}{7939}I told you Sid..
{7940}{7997}You’re not qualified to run a camp..
{7998}{8074}Oh! Since when do qualifications|have anything to do with childcare...?
{8075}{8121}Besides, these kids look up to me..
{8121}{8189}I’m a role model to them!
{8221}{8255}I can see that..
{8270}{8320}You guys never think I can do anything..
{8320}{8379}but I’m an equal member of this herd!
{8392}{8429}I made this herd...!
{8430}{8514}...and you need|to start treating me with some respect!!
{8566}{8602}Come on! Sid!
{8604}{8634}Sid! We were just kidding!!
{8646}{8670}Hey!
{8670}{8729}Let's play pin the tail on the mammoth!!
{8769}{8798}Sid!
{8825}{8877}Can you stop!
{8906}{8975}I'm gonna get some respect!!
{9042}{9067}I’ll show 'em!
{9097}{9163}And so, in the end..
{9166}{9221}the little burro reached his mommy..
{9242}{9302}and they lived happily ever after..
{9371}{9400}Good job!
{9400}{9468}Question! Why does the burro go home?
{9468}{9510}Why doesn't he stay with the rabbit?
{9522}{9607}Because. He wanted to be with his family
{9609}{9656}I think he should go with the girl burro!
{9657}{9696}...That's a better love story!
{9705}{9781}OK! Well, when you tell|your burro story, that’s what he'll do.
{9782}{9822}'Burro' is a demeaning name...
{9823}{9873}Technically, it's called a wild ass!
{9892}{9954}Fine. The wild ass boy came home...
{9955}{9993}...to his wild ass mother...
{10034}{10097}See! That’s why I called it a burro!
{10131}{10173}Could the burro have a grazing problem?
{10175}{10237}- That would make him more...relatable..|-Boring!
{10250}{10279}It’s not believable!
{10280}{10340}- Do burrows eat their young?|- It's not a very satisfying ending!
{10341}{10397}Sometimes I throw up!
{10420}{10460}They lived happily ever after...
{10460}{10526}You can't get more satisfying than that!
{10528}{10570}One big happy family!
{10576}{10609}That’s the way it’s supposed to be!
{10610}{10670}Then, where's your big, happy family?
{10800}{10875}Then...the|hungry tiger eat the pesky little kids!!
{10951}{10998}- You ok, buddy?|- Sure, why not?!
{10999}{11079}- I just thought you..|- Storytimes over....the end!
{11081}{11121}- Out of the way! Run for your lives!|- Hey, watch it!
{11122}{11152}Where's everybody going?
{11152}{11187}The world's coming to an end!
{11199}{11229}What are you talking about?
{11230}{11299}Fast Tony!|He says the world's going to flood!
{11313}{11376}Folks,|I hold in my hand a device so powerful..
{11377}{11406}it can actually pull air...
{11406}{11448}right out of the sky!!
{11453}{11499}Gather round...gather round!
{11522}{11581}Pardon me, do you have gills ma'am?
{11581}{11629}So you can't breathe under water?
{11648}{11694}My assistant here will demonstrate!
{11701}{11756}Hey, I can smell the ocean!
{11757}{11798}What are you doing...?
{11799}{11852}I can't sell that now...!!
{11853}{11907}You suck|air through your mouth you moron!!
{11926}{11996}If you're a pupil|of mine, and I'm starting instruction...
{11996}{12056}you'll|have plenty of air for eons to come!
{12074}{12134}Of course, don't stay buried!
{12152}{12209}Why are you scaring|everybody with this doomsday stuff?
{12236}{12276}I’m trying to make a living here pal..
{12338}{12379}It’s all part of my weather forecast!
{12380}{12452}The 5 day outlook is calling|for intense flooding, followed by..
{12455}{12505}the end of the world..!!
{12529}{12564}With a slight chance of patchy sunshine
{12564}{12594}..later in the week
{12606}{12652}Come on! Don't listen to him..
{12653}{12712}Fast Tony|would sell his own mother for a grape!
{12713}{12748}Are you making an offer?
{12757}{12818}I mean no! I would not!
{12827}{12881}Haven’t you heard? The ice is melting!
{12883}{12935}You see this ground? It's covered in ice
{12936}{12996}A thousand|years ago it was covered in ice..
{12997}{13029}A thousand years from now..
{13029}{13066}it will still be ice!
{13077}{13191}Say, buddy..not to cast aspersions|on your survival instincts, but..
{13191}{13255}haven't|mammoths pretty much gone extinct?
{13255}{13281}What are you talking about?
{13283}{13345}I’m talking|about you being the last of your kind!
{13358}{13428}Ahh! Your breath smells like ants!
{13503}{13535}Be as that as it may..
{13535}{13593}When's|the last time you saw another mammoth?
{13623}{13683}Ah! Don't pay any attention to him Manny
{13683}{13723}Mammoths can't go extinct..
{13723}{13763}they are the biggest things on earth!
{13763}{13803}What about the dinosaurs?
{13803}{13844}The dinosaurs got cocky!
{13844}{13881}They made enemies!|-Look!...
{13881}{13941}some idiot's going down the eviscerator!
{13943}{13998}Please tell me that’s not our cue!
{14043}{14143}OK..I'm goona jump on the count of 3!
{14183}{14243}One.....
{14247}{14271}Two.....
{14272}{14355}Sid!|Don't move a muscle! We’re coming up!
{14355}{14412}jump!..jump!...jump!..jump!..
{14412}{14446}...jump, jump, jump, jump!
{14453}{14474}Sorry..
{14493}{14543}Two and three one thousands...
{14544}{14587}Two and four one thousands...
{14589}{14648}Sid!|What are you doing? Get down from there!
{14648}{14714}No way! I’m going to be|the first to jump off the eviscerator...
{14715}{14762}And then|you guys are gonna have to start..
{14763}{14802}showing me some respect!
{14803}{14852}You jump off this|and the only respect you're gonna get..
{14853}{14885}is respect for the dead!
{14887}{14946}Come on Manny! He's not that stupid..!
{14973}{15015}But, I've been wrong before!
{15016}{15054}Geronimo!!!
{15147}{15171}Hey, watch it!
{15334}{15374}I can't breath...
{15396}{15447}I think I just coughed up my spleen!
{15803}{15873}Ahh! Diego! Retract the claws please!
{15873}{15915}Oh...right...sorry!
{15915}{15965}You know,|if I didn't know you better Diego..
{15965}{16015}I'd think you're afraid of the water..
{16019}{16088}Ok..Ok! Good thing I know you better!
{16089}{16118}Guys...!
{16134}{16178}Fast Tony was right..!
{16210}{16245}everything is melting!
{16863}{16899}It’s all gonna flood...
{16907}{16938}Come on! We’ve gotta warn them.
{16968}{17035}Maybe we can|rapidly evolve into water creatures.
{17036}{17077}That’s genius, Ed...
{17079}{17114}Call me 'Squid'.
{17171}{17224}Gees..this whole thing's a piece of junk!
{17229}{17268}I can't believe I live here!
{17344}{17382}What?
{17514}{17542}I can breathe..
{17549}{17613}I present you|with this revolutionary gizmo, we call..
{17613}{17637}Bark!!
{17637}{17685}It’s so buoyant, it actually floats!
{17686}{17736}I'll show you something that floats!
{17764}{17824}Alright.... it's your funeral!
{18065}{18128}You see!|This is exactly what I’m talking about!
{18128}{18165}Giant balls of fury larva...
{18165}{18192}the size of mammoths...
{18193}{18219}raining from the sky!!
{18224}{18279}Ahh! Go suck air through a reed!
{18298}{18354}You gotta listen|to him! He’s right about the flood!
{18354}{18366}I am?
{18366}{18426}I mean...uh...Yes, I am!
{18438}{18474}Wait a minute! You're the one who said..
{18475}{18504}there wasn't going to be a flood!
{18504}{18539}Why should we listen to you?
{18546}{18594}Because we saw what’s up there!
{18601}{18670}The dam's|gonna break. The entire valley is gonna flood!
{18748}{18770}Flood’s real alright..
{18792}{18836}and it's coming fast!
{18848}{18913}Look around! You're in a bowl..!
{18946}{18988}Bowl's gonna to fill up...!
{18989}{19034}Ain't no way out...!
{19069}{19089}What are we going to do?!
{19092}{19170}Unless, you can|make it to the end of the valley..
{19183}{19246}there's a boat...It can save ya!
{19254}{19290}I don't see anything..
{19290}{19314}Fine..
{19329}{19412}You all better hurry..ground’s melting..
{19413}{19485}walls tumbling..rocks crumbing..
{19492}{19567}survive that,|and you'll be racing through water!
{19571}{19609}coz in 3 days time..
{19612}{19662}It’s going to hit the geyser fields..
{19668}{19686}Boom!!!
{19749}{19796}There is some good news though!
{19810}{19852}The more of you die..
{19860}{19907}the better I eat!!
{19939}{20019}I didn't say it was good news for you..
{20105}{20167}He must have been|a real pleasure to have in class!
{20765}{20787}Damn!
{20821}{20860}Alright! You heard the scary vulture..
{20869}{20905}Let’s move out!
{20930}{20981}Manny..|Do you really think there's a boat?
{20984}{21035}I don't know..|But in a few days this place..
{21036}{21077}is gonna to be a mile under water..
{21077}{21124}If there's any hope...it's that way
{21643}{21692}Manny, lets go!
{22206}{22272}We’ve got an|overturned cliff on the far right lake..
{22272}{22322}traffic is|packed up as far as the eye can see..
{22331}{22386}Ohhh! And|it looks like there might be a fatality!
{22416}{22458}I call the dark meat!!
{22481}{22571}Come on everybody! Lets go!|Come on. Come..come..come! Get in!
{22631}{22732}Come on Granpa, come on! We have to go!
{22732}{22765}Well, I’m not leaving!
{22767}{22847}I was born|in this hole and I'll die in this hole!
{23028}{23093}Do we have to bring this crap..?
{23098}{23158}I’m sure there's crap where we're going!
{23161}{23207}Ahh! This was a gift from my mother!
{23227}{23292}- Ok! Keep it moving..keep it moving!|- Manny, Manny!
{23294}{23336}I've just heard you’re going extinct!
{23339}{23391}Hey! If you ever master hygiene..
{23392}{23432}try working on sensativity!!
{23440}{23475}I’m not going extinct!
{23476}{23500}Kids! Look...!
{23521}{23564}The last mammoth!
{23614}{23685}Well, you probably|won't see another one of those again!
{23688}{23713}See?!
{23755}{23797}Where is James?
{24735}{24799}Stu! Come on! Stu!
{24801}{24848}Lets blow this ice cube stand!
{24895}{24920}Stu!!
{25069}{25163}Folks! Be the first in the valley|to have your very own mobile home!
{28248}{28353}Some day, when you're gonna sing..
{28357}{28402}When you make us sing...
{28407}{28452}- Shut up Sid!|- Ok!
{28472}{28531}Stop, hey-hey...What’s that sound..?
{28532}{28622}- All the mammoths are in the ground.|- Stop singing Sid!
{28758}{28841}Sid! I’m gonna fall on you|again! And this time I will kill you!
{28843}{28928}Ok..someone doesn't like the classics!
{29177}{29228}What if you're right?
{29232}{29286}What if I am the last mammoth?
{29286}{29357}But Manny,|look on the bright side..you have us!
{29358}{29428}Not your most persuasive argument, Sid!
{29537}{29561}Mammoths?
{29561}{29602}I knew I couldn't be the last one!
{29602}{29644}I felt it in my trunk!
{29943}{29963}This stinks!
{29963}{29993}Come on!
{30416}{30470}Sorry! My stomach...
{30474}{30542}hates me!
{30561}{30616}Well...|Don't that put the 'stink' in extinction!
{30624}{30644}Whooa!
{30652}{30672}Sheesh!!
{30677}{30722}Oooh....Nasty!
{30799}{30822}Manny?
{30850}{30936}I ah..I need to be alone for a while..
{30949}{31038}You go on ahead..I'll catch up!
{31187}{31260}One truly is the lonliest number...
{31267}{31312}-Ow!|-Ow!...Hey!
{31332}{31375}Ohh..these work great!!
{31407}{31427}Cool!
{31478}{31532}Missed me...missed me!|Try and come and kiss me!!
{31532}{31558}I’ll get 'em!
{31603}{31633}Which end is up?
{31638}{31673}I dunno..That makes two!
{31684}{31715}Hey, ugly!
{31718}{31759}Ow!...I've got to sit on that!
{31889}{31909}Got you!
{32081}{32128}Ok! I’m going in!
{32158}{32198}- Sid!|- What?!
{32257}{32292}I felt some breeze in that one!
{32299}{32319}Smile!
{32505}{32541}Over here!
{32606}{32646}- Surrender?|- Never!
{32646}{32671}Cool!!
{32908}{32958}If any one asks..there were 50 of them..
{32958}{33008}...And...they were...rattlesnakes!
{33043}{33070}Here kitty-kitty..
{33071}{33116}Big mistakes you miscreants!
{33117}{33151}Miscreants?
{33183}{33253}Uh..Diego, they're pecking..
{33316}{33351}Retreat!
{33993}{34053}I guess it's just you and me now..
{34343}{34411}I knew it! I knew I wasn't the only one!
{34415}{34480}Me too! Everyone falls|out of the tree every now and then..
{34480}{34511}they just don't admit it!
{34511}{34540}Wait...what?
{34550}{34610}Some of us|have a tough time holding on to branches
{34612}{34654}I mean|it's not like we're bats or something..
{34654}{34711}We don't have wings to keep us up!
{34719}{34813}And you were in the tree..because?
{34822}{34853}I was looking for my brothers..
{34855}{34894}They are always getting into trouble..
{34900}{34958}Brothers? You mean there's more?
{34967}{34983}Sure!
{35034}{35052}..lots of us
{35061}{35080}Where?
{35102}{35134}Everywhere..
{35135}{35180}under rocks and holes in the ground...
{35187}{35258}Usually we come out|at night, so birds don't carry us off!
{35287}{35338}Help! Help!
{35473}{35528}Well!!|Shave me down and call me a mole-rat!!
{35530}{35576}You’ve found another mammoth!
{35587}{35599}Where?
{35617}{35673}Wait a minute!|I thought mammoths were extinct!
{35711}{35737}What are looking at me for?
{35744}{35768}I don't know..
{35769}{35820}Maybe because you are a mammoth?
{35830}{35839}Me?!
{35861}{35932}Don’t be ridiculous!|I’m not a mammoth! I’m a possum!
{35936}{35980}Right, good one! I'm a newt...
{35980}{36024}This is my friend, the badger..
{36028}{36081}and my other friend the platypus!
{36082}{36150}Why do I got to|be the platypus! Make him the platypus!
{36169}{36214}This guy giving you trouble, Sis?
{36216}{36239}Sis?
{36252}{36312}That’s right, these are my brothers..
{36315}{36376}Possum....Possum....Possum
{36393}{36462}I don't think her|tree goes all the way to the top branch!
{36527}{36597}Manny, the brink|of extinction is a bad time to be picky
{36603}{36651}Hey...She should come with us!
{36658}{36716}Are you insane? No way!
{36724}{36818}Ok! Manny wants me to ask you if|you'd like to escape the flood with us
{36823}{36838}What the?
{36864}{36898}I’d rather be road kill!
{36900}{36934}That could be arranged!
{36937}{36967}Ha....funny!
{36989}{37053}Let me|have a little word with my brothers..
{37058}{37131}Ellie!|Are you crazy? We’re not going with them!
{37134}{37217}Look! We’ll never make|it in time if we only travel at night..
{37221}{37313}These guys can protect|us out in the open. What do you say?
{37339}{37393}- Ow!|- Why did you invite them?
{37396}{37479}Because you might|be the only two mammoths left on earth.
{37479}{37507}He has a point!
{37508}{37576}I’m sorry.|When did I join this dating service?
{37588}{37654}My brothers and I|would be delighted to come with you..
{37679}{37750}if...you treat us nicely!
{37751}{37813}See that!|That’s the total opposite of nice!
{37813}{37879}Maybe we'll have ourselves|a little snack before we hit the road
{37881}{37942}Want a piece of us? lets go!
{37947}{37977}Bonsai....!
{37989}{38030}- I got him!|- Ow!
{38090}{38114}You know the best part...?
{38115}{38173}We’re carrying diseases!
{38327}{38382}Ok! Thanks to Sid...
{38383}{38421}we're now travelling together...
{38423}{38453}and like it or not...
{38453}{38508}we're going to be one big happy family!
{38511}{38540}I’ll be the daddy..
{38541}{38585}Ellie will be the mommy..
{38588}{38673}And Diego will be the uncle|who eats the kids who get on my nerves!
{38684}{38753}Now let’s move, before the|ground falls out from under our feet!
{38775}{38844}I thought|fat guys are suppose to be jolly..
{38845}{38923}I’m not fat!|It’s this fur that makes me look big!
{38943}{38967}It’s poofie!
{38983}{39052}Ok..he's fat..
{39891}{39932}Folks! Escape from the flood is a..
{39933}{39995}perfect time|to shed those unsightly pounds...
{39995}{40064}with fast Tony's....disaster diet!
{40104}{40174}You, ma'm!|You look like a big fat hairy beast!
{40187}{40251}How'd you|like to lose a tonne or two of that?
{40254}{40290}Would I ever!!..
{40301}{40337}Don’t listen to him, Vera!
{40350}{40400}You’re already thin as a twig..
{40421}{40499}I also have the perfect|cure for your eyesight, my blind friend!
{41249}{41299}Ohh...We'll never make it at this pace!
{41301}{41371}Ellie, it's ok!|You can lose the camouflage!
{41375}{41400}You’re safe!
{41400}{41459}Ok....safe?
{41460}{41496}Please!! Crash....Eddie...
{41496}{41526}You two...Go scope it out!
{41527}{41577}- What you got?|-Perimeter looks to be all clear captain
{41582}{41623}Roger that..four-niner, over!
{41624}{41676}Roger. Over!
{41724}{41747}All clear!
{41906}{41935}Hawk!!
{42126}{42166}What are you doing?
{42168}{42208}Playing dead..!
{42211}{42266}Manny...Why don't you do that?
{42271}{42311}Because, I’m a mammoth!
{42311}{42373}But you do it for treats, right?
{42386}{42411}Is he gone?
{42497}{42543}You’re safe! Get up..
{42590}{42636}Man!...if you weren't here..
{42638}{42676}that hawk would have swooped down..
{42676}{42711}and snatched me up for dinner!
{42715}{42769}That’s how Cousin Wilson went!
{42856}{42907}Boy, I really feel for you, I do!
{42911}{42956}I can't|even imagine what it would be like...
{42956}{43012}to be the last one of your species!
{43021}{43061}I’m not the last one!
{43066}{43117}Oh...You brave, brave soul....
{43127}{43182}that's right, don't give up hope..
{43225}{43238}Ellie?
{43283}{43318}Look at our footprints....
{43346}{43375}they're the same shape
{43416}{43460}Well, how|do I know those aren’t your footprints?
{43484}{43511}Well...then..
{43541}{43610}look at our shadows..we match!
{43650}{43708}You’re right! We’re the same!
{43720}{43783}You must be part possum!
{43850}{43885}You wish!
{44211}{44288}Diego, there are whole continents|moving faster than you...lets go!
{44288}{44343}We got to catch up with the others!
{44556}{44596}Hey! Knock it off!!
{44672}{44750}Oh cry me a river,|blubber tooth tiger. Have some fun!
{44757}{44842}Can’t you see the ice is thin|enough..without you two wearing it down?
{44849}{44914}Oh, Diego. The ice may be|thin, but its strong enough to hold...
{44918}{45000}a ten ton mammoth and a nine ton possum!
{45977}{46052}Ellie...get up!|If you play dead...you'll be dead!
{46067}{46107}Look at me!
{46265}{46289}Diego?
{46502}{46521}Diego!
{46765}{46788}Come on....
{46802}{46829}Come on!
{46862}{46897}This may sting a little..
{48475}{48522}What in the animal kingdom was that?
{48526}{48594}I don't know,|but from now on...playing safe..!
{48594}{48638}Water? Not safe!
{48793}{48853}That.....|was the bravest thing I've ever seen..
{48855}{48896}It was nothing really, I..
{48902}{48935}Oh! It's not a compliment...!
{48937}{48980}To a possum...bravery is just dumb!
{48983}{49013}Yeah! We’re spineless..
{49014}{49048}Lily-livered!
{49054}{49098}Maybe mammoths are going extinct because
{49100}{49151}they put themselves in danger too often!
{49152}{49191}Maybe you should run away more!
{49218}{49271}Good point! Thanks for the advice!
{49276}{49306}Happy to help!
{49342}{49373}Do you believe her?..
{49376}{49450}"Bravery is just dumb!|Maybe you should just run away more.."
{49458}{49541}She’s infuriating|and stubborn and narrow-minded!
{49547}{49587}You like her...
{49592}{49618}I do not!
{49627}{49691}Don’t worry; your secret is safe with me!
{49694}{49763}- Oh...and so is yours..|- What secret?
{49769}{49828}You know..|...the one where you can't swim
{49838}{49867}That’s ridiculous!
{49872}{49922}Fine, but we're|living in a melting world buddy!
{49929}{50007}You’re gonna have|to face your fears...sooner...or later
{51523}{51560}Ok! Ready Eddie?
{51561}{51618}Set! Let’s roll!
{51689}{51716}Wait for me!!
{51999}{52026}Don’t wait....gotta roll...
{52036}{52065}meet you at the other end!
{52093}{52160}So, you think she's girl for me?
{52160}{52198}Oh, yeah. She's tons of fun...
{52201}{52226}and you are no fun at all!
{52240}{52283}She completes you!
{52351}{52376}Yeah, yeah!!
{52391}{52418}Hey! Hey, Manny!
{52451}{52476}Can you pull back the tree...
{52476}{52512}- and shoot me in the pond?|- No!
{52522}{52545}Aw...come on..
{52562}{52626}Now..how do you expect|to impress Ellie with that attitude?!
{52626}{52678}- I don't wanna impress her!|- Then why are you trying so hard to...
{52679}{52723}...convince her that she's a mammoth?
{52725}{52764}Because, that's what she is!!
{52773}{52816}I don't care|if she thinks she's a possum....
{52818}{52853}You can't be two things!
{52858}{52899}On contraire.....my...friend!
{52921}{52988}Tell that to the bullfrog,|the chicken hawk or turtle-dove!
{52990}{53026}He's never gonna let up on you!
{53031}{53087}It'll be easier if you just go with it!
{53177}{53215}So, what you want me to do?
{53223}{53245}Pull back the tree...
{53251}{53285}...and shoot me into the pond!
{53297}{53317}I don't know..
{53336}{53380}Well, if you are too lame to do it...
{53381}{53431}- we can get Ellie.|- No..no..no....no..
{53431}{53458}I can do it, I can do it!
{53473}{53522}Yeah..yeah. Come on..come on!
{53523}{53559}Have you done this before?
{53560}{53607}Ha! Only a million times!
{53613}{53671}Farther, farther, farther...
{53689}{53710}Perfect...!
{53724}{53742}Fire!
{53822}{53871}I can fly...!
{53895}{53955}I believe I can fly..
{54141}{54166}Crash!!
{54234}{54269}Crash, Crash!!
{54294}{54351}Crash, you ok? What happened?
{54356}{54402}Manny shot him out of the tree!
{54404}{54424}What’s wrong with you?
{54424}{54457}He said he could do it!!
{54461}{54494}...and you listened to him!
{54513}{54548}Crash, whatever you do...
{54548}{54586}don't go into the light!
{54590}{54624}Can I help in anyway here?
{54643}{54668}You've done enough!
{54730}{54761}Are you happy now?
{54766}{54825}Crash..Crash..don't leave me!
{54828}{54891}Who's gonna watch my back?
{54902}{54964}Who’s gonna be my wee man of mayhem?
{54967}{55085}Who’s gonna|roll in that dung patch with me?!!
{55092}{55120}Dung patch?!
{55134}{55180}Wait...! My legs...!
{55185}{55223}I can stand!
{55225}{55287}- He can stand!|- I can run!
{55288}{55343}- He can run! It’s a miracle!
{55344}{55377}Hallelujah!
{55540}{55589}What can I say?... They're boys...
{55604}{55641}...they make|my life a little adventure!
{55668}{55713}You guys are so dead!
{56114}{56134}She's not half bad...
{56196}{56242}crazy and confused, but..
{56256}{56279}Sweet!
{56282}{56297}So?
{56369}{56410}So what’s holding you back?
{56485}{56507}My family
{56616}{56666}You can have that again, you know...
{56685}{56726}No, Sid. I can't!
{56760}{56850}Ok, ok. But, but, but, think about it!|I mean if you let this chance go..
{56850}{56940}you're just letting your whole speices|go! And that's just...that's just.....
{56947}{56966}..selfish!
{57130}{57190}I think|I'm starting to get through to him!
{57230}{57274}Wait, wait! I got you!
{57403}{57431}Need help?
{57433}{57498}No, no! Just catching my breath...
{57512}{57565}- You're stuck.|- I am not!
{57572}{57610}Alright then, let’s go..
{57671}{57704}I can't...
{57731}{57761}I'm stuck!
{57771}{57803}Don't you think that..
{57804}{57845}picking them up like this..
{57845}{57895}would be easier?
{58278}{58301}Ellie?
{58851}{58900}I know this place...
{61890}{61911}You know....
{61921}{61981}deep down, I knew I was different..
{62046}{62117}I was a little|bigger than the other possum kids..
{62149}{62201}Ok, a lot bigger!
{62221}{62301}Oh! Now I|understand why the possum boys..
{62302}{62349}didn't find me appealing!
{62349}{62380}That’s too bad...
{62381}{62446}Because, as far as mammoths go, you're..
{62491}{62546}- you know...!|- What?
{62664}{62694}Attractive!
{62699}{62729}Really?
{62757}{62825}- Sure...|- What about me is attractive?
{62870}{62933}Well, I don't know...
{62966}{63042}well...there's you're...uh...
{63043}{63068}butt?
{63110}{63148}What about it?
{63175}{63211}It’s....
{63227}{63257}big?
{63284}{63344}Oh, you're just saying that!
{63350}{63394}No, no...
{63397}{63451}No, I mean it! It's huge..!
{63454}{63507}biggest darn butt I've ever seen...
{63512}{63578}Oh...that is really sweet!
{63597}{63647}What a crazy day!
{63651}{63715}This morning I woke up a possum...
{63717}{63781}and now...I'm a mammoth!
{66325}{66398}Boy, Manny|sure took a big leap with Ellie today...
{66403}{66450}- He sure did.|- Yup
{66453}{66493}He stood on the shore of uncertainty...
{66502}{66563}and dove right in...Splash!!
{66564}{66610}Kind of brave, huh...?
{66615}{66658}the way he faced his...fear!
{66660}{66693}I wouldnt know...
{66695}{66726}Sabre's don't feel fear!
{66731}{66785}Oh, come on! All animals feel fear..
{66788}{66828}It’s what separates us from safe!
{66831}{66885}Rocks! Rocks have no fear...
{66903}{66938}and they sink!
{66955}{66991}What are you getting at, Sid?
{66993}{67045}It may surprise you to know that I too..
{67047}{67105}have experienced....fear!
{67106}{67180}- No! You?|- Oh, yes!
{67180}{67223}As impossible as it seems...
{67226}{67281}the sloth|has natural enemies that would like to..
{67285}{67321}harm, or otherwise...
{67326}{67357}kill us!
{67361}{67394}I wonder why!
{67396}{67456}Oh, jealousy mostly. But the point is...
{67458}{67501}that fear is natural!
{67523}{67573}Fear.....is for prey!
{67583}{67638}Well then...|You're letting the water make you..
{67638}{67668}it's prey!
{67677}{67730}Just jump in and trust your instincts!
{67772}{67832}You know,|most animals can swim as babies...
{67837}{67861}and for a tiger...
{67864}{67912}It’s like crawling on your belly...
{67921}{67963}to stalk helpless prey!
{68004}{68035}Put that hunt on, ok?!
{68050}{68110}Now, claw, kick, claw, kick...
{68110}{68144}I'm stalking the prey!
{68144}{68192}Claw, kick...now...
{68192}{68221}I look back over my shoulder..
{68221}{68254}to see if I am being followed...
{68257}{68284}and I’m breathing!
{68314}{68374}and I'm stalking and I'm stalking...
{68429}{68466}I am falling...
{68479}{68526}Correction! You're sinking...
{68538}{68575}kind of like a rock!
{68715}{68762}Hey, do we do any special tricks like...
{68768}{68802}roll over? Or do we just...
{68804}{68826}throw our weight around?
{68881}{68937}Sorry,|I don't know my own strength yet!
{68971}{69015}Ellie, do you realise that...
{69015}{69066}now|we have a chance to save our species?
{69076}{69117}Really? How are we going to do that?
{69129}{69180}Well, you know...
{69180}{69222}-Oh! Uh, uh! Did you just?!|-No...
{69222}{69279}- I didn't mean.|- I'm not a mammoth for five minutes..
{69279}{69315}... and you're hittin' on me?
{69318}{69352}I wasn't saying...
{69352}{69388}not right now. I'm...
{69391}{69416}in time...!
{69423}{69461}I was just saying that it’s..
{69461}{69489}our responsibility...
{69496}{69560}- What?!|- That came out wrong!
{69589}{69614}You're very pretty...
{69614}{69642}But, we just met...
{69642}{69676}Responsibility...?!
{69676}{69721}Just doing your duty, huh? Is that it?
{69726}{69766}Ready to make the ultimate sacrifice...
{69769}{69811}to save your species!
{69819}{69847}Well, I got some news for you..!
{69851}{69898}You not saving the species tonight...
{69905}{69941}or any other night!
{70194}{70234}So, how did it go?
{70242}{70282}Hmm! Not bad...
{70409}{70452}Ok, let’s go!
{70456}{70495}We traveled with you all day...
{70504}{70537}now you coming with us at night!
{70540}{70589}but we can't see at night
{70595}{70641}Then enjoy...the flood!
{70652}{70702}I can't even look at him!
{70724}{70754}Pervert!
{70878}{70902}Making friends..
{70909}{70973}everywhere you go! Just making friends!
{71583}{71618}Watch out, there's a stump!
{71621}{71648}Not anymore...
{71697}{71757}I thought we could walk together
{71767}{71819}Crash, ask the man why he thinks that?
{71832}{71876}She said she thinks you are a jerk...
{71880}{71906}and to go away!
{71915}{71956}She didn't say...Oww!
{71978}{72040}Look! Maybe if we spend more time..
{72057}{72136}Tell him that I need|a little personal space right here!
{72157}{72197}She said...go jump in a lake...
{72197}{72238}and possums rule!
{72271}{72312}I can hear her, you know?
{72313}{72348}What do you want? A medal?
{72629}{72672}Stop moving!
{72766}{72788}Thank you!
{72989}{73045}Manny, Ellie! Lock trunks..!
{73109}{73125}Now!
{73266}{73324}Crash, Eddie! Grab onto that ledge!
{73484}{73528}Funny!  And now, what's your real plan?
{73531}{73559}Just do it!!
{73574}{73611}- Bye Eddie|- Bye Crash
{73620}{73671}- Bye Ellie|- Go now!
{73786}{73806}I'm sorry..
{73815}{73873}if what l said before offended you!
{73875}{73925}What do you mean 'if' it offended me?
{73949}{73988}"That" it offended her...!
{73989}{74025}"That" it offended her!!
{74025}{74082}I mean "that"..."That" it offended you..!
{74182}{74223}You just overreacted, that's all..
{74235}{74275}What?! Take it back!
{74275}{74326}There are other lives at stake here!
{74327}{74360}Wait a minute! He's got a point!
{74360}{74387}He’s got nothing!
{74387}{74447}- It was a misunderstanding!|- It was insensitive!
{74450}{74480}Apologize!
{74482}{74522}Why me? She overreacted...!
{74522}{74552}Just apologize!!
{74553}{74589}- No!|- Do it!
{74589}{74640}Ok... I'm sorry!
{74640}{74664}What?!
{74687}{74732}He's right. I overreacted
{74737}{74749}You mean, you...?
{74749}{74784}Not another word or I’ll come down there
{74786}{74832}...and push you over myself!
{75040}{75065}Oh Oh!
{75135}{75171}Manny! Ellie! Run!
{75490}{75541}I guess|we finally did something right together!
{75577}{75611}Hey, don't mind me...
{75612}{75662}just hanging off the cliff here!
{76177}{76217}Remember the good old days?
{76219}{76248}Which good old days?
{76249}{76328}Oh, you know. Yesterday...last week...
{76334}{76372}Back when the trees when up and down...
{76372}{76429}and the ground stayed under our feet!
{76466}{76517}Yup! Those were the good days!
{76532}{76572}Possums were possums and...
{76578}{76602}mammoths were mammoths...!
{76640}{76663}We should get some sleep...
{76682}{76754}Yeah, tomorrow is the day|the vulture said we're all gonna die!
{78090}{78136}No, no, no. I dont wan't any....
{78413}{78435}No, no, no....no...
{78614}{78644}Wait a minute!
{78686}{78714}Can I help you?
{78979}{79048}Hmmm! Now, that’s what I call respect!
{79110}{79141}Nice!
{79291}{79355}Somebody here likes Sid...!
{79375}{79410}Who is the decorator...?
{79410}{79456}I mean, this is fablulous...!
{79591}{79652}- Fire king..|- Huh?
{79801}{79845}Fire king?...hmm!
{79846}{79879}Well. You know, it's about time...
{79880}{79940}someone recognised my true potential!
{79943}{80006}Let there be fire!!
{81667}{81740}If only the guys could see me now!
{81768}{81805}This is either really good
{81806}{81845}or...really bad..!
{81900}{81959}Oh! No, no, no! Me fire king...
{81960}{82015}Why kill fire king? A thousand years...
{82015}{82067}bad ju-ju for killing fire king!!
{82076}{82126}Superheated rock from the Earth's core..
{82126}{82165}is surging to the crust, melting ice...
{82165}{82213}built up over thousands of years!
{82214}{82262}You're a very advanced race. Together...
{82263}{82300}we can look for a solution!
{82309}{82363}We have one!..Sacrifice the fire king!
{82368}{82407}Well, thats not very advanced...
{82412}{82431}Worth a shot...!
{82897}{82928}Bad ju-ju!!
{83466}{83509}Water?  Water!!
{83658}{83715}Crash,|I told you not to drink before bed!
{83715}{83739}I didn't do this...!
{83762}{83797}At least not all of it!
{83805}{83857}- What’s happening?|- We overslept...
{83858}{83884}We need to move
{83885}{83938}What if we're last creatures left alive?
{83946}{84011}- We'll have to repopulate the earth!|- How...?
{84020}{84076}Everyone’s either a dude or a sister!
{84109}{84128}Hi
{84136}{84162}Hi, hey Manny...
{84165}{84233}Wow, what a night!|You'll never guess what happened to me..!
{84236}{84292}I'm going to go out on a limb|here and say you were sleepwalking
{84293}{84332}Oh, no, no, no. I was....
{84334}{84377}kidnapped by a tribe of mini-sloths..
{84382}{84426}That was going to be my second guess!
{84428}{84462}and they worship me...
{84463}{84528}I mean sure,|they tossed me into a flaming tar pit..
{84529}{84568}but they worship me!!
{84570}{84627}Sid, you were dreaming! Come on...
{84628}{84670}The water's|rising faster than we're moving!
{84671}{84716}I'm telling you! I was kidnapped...
{84724}{84768}I was worshipped and they...
{84770}{84839}Guys?! Oh, fine!
{85008}{85043}Can we slow down a little...?
{85057}{85101}I'm dying here...
{85199}{85249}It was just a figure of speech!!
{85378}{85415}They just sit there...
{85431}{85464}watching us!
{85473}{85514}I wish l knew what they were thinking...
{85616}{85702}Food, glorious food...
{85703}{85779}we're anxious to try it....
{85787}{85861}Three banquets a day....
{85861}{85927}our favorite diet!
{85933}{85999}Just picture a mammoth steak....
{86000}{86062}- fried, roasted....or stewed....|- Oh....
{86063}{86111}food, wonderful food...
{86120}{86160}marvelous food...
{86160}{86257}glorious.....fooood!!
{86280}{86340}Food, glorious food...
{86343}{86411}poached possums or flambé!
{86418}{86479}Broth made from a sloth...
{86479}{86548}or savored to soufflé!
{86557}{86619}Why should we debate it? True...
{86620}{86668}you've nothing, but food!
{86668}{86705}Oh....foood...
{86706}{86762}magical food, wonderful food...
{86770}{86845}marvelous foood!
{86873}{86941}Food, glorious food...
{86941}{87009}Flesh, picked off the dead ones!
{87013}{87073}We're famished for food...
{87074}{87147}soon, we'll be the fed ones!
{87151}{87211}Just thinking of putrid meat...
{87211}{87266}puts us in the mood!
{87266}{87333}Oh, food, glorious food...
{87334}{87394}marvelous food, wonderful food...
{87394}{87441}beautiful food...
{87449}{87516}magical food...
{87517}{87613}glorious......
{87613}{87723}Foood!!
{87775}{87792}There...
{87798}{87846}now you know what they were thinking!
{87919}{87996}- Food, glorious food...|- Sid!!
{88004}{88048}What?!  It's catchy!
{88354}{88439}- We made it!|- Yeah, we showed those scary vultures!
{89067}{89121}Oh, it's just a little hot water and steam!
{89122}{89154}How bad could it be?
{89320}{89374}I just did something involuntary...
{89385}{89409}and missed!
{89439}{89463}Ok, come on!
{89512}{89546}Manny! Get back!!
{89546}{89579}It's a mine field out there!
{89585}{89631}There's only one way to go...
{89631}{89682}- Straight through!|- Straight through?
{89683}{89747}We'd like to|keep the fur on our bodies, thank you!
{89750}{89779}We'll head back, then we'll go around...
{89779}{89798}Thats safer!
{89798}{89836}No, no! There's no time...
{89837}{89874}the dam will burst before we make it...
{89874}{89924}- We'll drown!|- If we go through this....
{89925}{89957}we get blown to bits!
{89960}{90002}- We go forward!|- We go back!
{90003}{90032}- Forward!!|- Back!!
{90032}{90059}- Forward!!!|- Back!!!
{90059}{90108}- Can I say something?|- No!!
{90123}{90204}You are so stubborn and hard headed...
{90204}{90239}Well, I guess that proves it...
{90243}{90293}I am a mammoth!
{90328}{90354}Come on!
{90387}{90404}Fine!
{90415}{90451}I don't know! Drowning sounds like a...
{90452}{90486}much gentler way to go...
{90491}{90533}Blown to bits sounds so....
{90545}{90579}sudden!
{90827}{90867}Ah! He's gonna get himself killed!
{90878}{90902}Manny, wait!
{90917}{90937}Manny?!...
{91512}{91536}"...Kids, look..."
{91537}{91580}"...the mad mammoth..."
{91581}{91618}"...ends up going extinct..."
{91634}{91666}"...You can't be two things...."
{91666}{91694}"...She thinks your a jerk..."
{91694}{91721}"...and to go away..."
{91727}{91769}"...Where's your big happy family?..."
{91790}{91825}"...What's wrong with you...?"
{91858}{91920}Hey, come on! We got to go..now!!
{92080}{92100}That way!
{93078}{93134}Do not leave your children unattended...
{93149}{93214}all unattended children will be eaten...
{93315}{93351}- Have you seen a Mammoth?|- No, sorry.
{93365}{93410}- Have you seen a Mammoth?|- No. No, I haven’t!
{93421}{93470}Possum, about 11 foot tall?
{93537}{93577}Hey, buddy, have you seen a mammoth?
{93580}{93631}- I sure have...big as life!|- Where?
{93638}{93665}I'm looking at him!
{93673}{93697}Not me!!
{93723}{93768}Poor guy! Doesn’t know he's a mammoth!
{95206}{95241}I don't see her anywhere!
{95246}{95293}Maybe she is already on board!
{95623}{95652}All right, keep quiet!
{95652}{95675}Come on, get moving!
{95739}{95765}There it is!!
{95771}{95792}Ellie...!
{96031}{96072}Come on, come on! Run!
{96243}{96268}Push!!
{96349}{96381}You guys got to go...
{96381}{96413}We're not leaving you!!
{96433}{96481}- I’m not asking!|- Ellie! No!
{96561}{96618}Ellie, don't worry! We're going for help
{96618}{96652}Stay here!
{97017}{97107}Help us! Somebody help!
{97108}{97123}Manny!
{97172}{97197}Manny...!
{97311}{97327}Manny...
{97328}{97377}It's Ellie! She's trapped in a cave!
{98833}{98849}Ellie!!
{98877}{98904}Manny?!
{99001}{99031}Help!
{99031}{99066}I'll save you...!
{99192}{99240}Great! Who's gonna save him?
{99307}{99351}You really need to brush!
{99486}{99540}Okay, okay, okay! Jump in...
{99550}{99563}Now!
{99601}{99656}Come on...break it...Come on!
{99669}{99709}You can do this,|you can do this...you can do this!
{99726}{99744}Help!
{99757}{99813}Trust your instincts! Attack the water..
{99815}{99871}I am not your prey, I am not your prey..
{99872}{99927}I am not your prey!!!
{100476}{100530}Hector...stalking the prey...
{100531}{100609}Come on...kick! Even babies can do it..!
{100610}{100669}Come on...claw...kick...
{100670}{100715}claw...kick...
{100727}{100787}Hey! I'm stalking the prey!
{100939}{100964}Eddie!
{101315}{101352}You did it buddy...
{101362}{101411}You kicked waters butt!
{101417}{101493}Nothing to it! Most|animals can swim as babies you know!
{101494}{101532}Yeah, but not tigers...
{101532}{101572}I left that part out!
{101942}{101972}There he is...!
{102015}{102064}Ellie, hold on to me!
{102834}{102892}Manny! They're behind you!
{103782}{103847}There they are! Yeah!
{104158}{104218}We thought we'd never see you again!
{104454}{104495}We're gonna live!
{104604}{104647}We're gonna die!
{107026}{107046}Manny...!
{107399}{107429}Well, I’m not leaving!
{107442}{107510}Granpa,|let go of the boat! The flood is over!
{107511}{107547}This is my boat now!
{107643}{107718}Hey Stu...we made it! We're gonna live!
{107731}{107778}Well, I am anyway..
{107808}{107854}- I'm gonna get you...!|- Oh, no you won't...
{107856}{107914}I don't know,|I’m thinkin about startin a swim school!
{107918}{107967}"Sid's squids"!
{108099}{108150}All hail, fire king!
{108279}{108312}Uh...Hi?
{108316}{108354}Hi! Hi! Hi! Hi! Hi!
{108435}{108484}Fire king avert flood...
{108485}{108575}Join us, oh great and noble flaming one!
{108591}{108607}Hmmm....
{108632}{108690}Whoa! No, not so fast there, okay?
{108694}{108744}You...you make a quality offer...
{108744}{108801}but fire king has a...
{108801}{108829}prior committment...!
{108842}{108881}His herd needs him!
{108902}{109009}He is the gooey, sticky, stuff that...
{109014}{109052}holds us together!
{109078}{109131}He made this herd and...
{109160}{109206}we'd be nothing without him!
{109221}{109242}You mean it?!
{109311}{109361}That doesn't mean...want to touch...
{109512}{109534}Don't ask!
{110638}{110671}Whoaaa!
{111009}{111062}We're not the last ones anymore!
{111205}{111236}You're not coming?
{111257}{111294}You wanna go with them?
{111314}{111343}I am a mammoth...
{111367}{111414}I should probably be with a mammoth...
{111427}{111458}don't you think?
{111488}{111521}Yeah, unless...
{111582}{111610}Unless..
{111668}{111722}Unless..I...ah...
{111785}{111826}I just wanna say..
{111873}{111909}I need to tell you..
{111972}{112031}I hope|you find everything you're looking for!
{112149}{112174}You too..
{113023}{113039}Manny...?
{113066}{113124}You've come a long way since we met..
{113124}{113169}and I’ll take full credit for that...
{113170}{113224}But you need to let go of the past...
{113225}{113278}so you could have a future!
{113380}{113420}Go after her!
{113430}{113456}It’s okay...
{113479}{113516}We'll always be here for you..
{113546}{113571}I’ll keep in touch...
{113585}{113633}Yeah, yeah, yeah. You're a good friend..
{113640}{113709}..point made. Now, go on, scat!
{113858}{113907}Our Manny's growing up!
{113940}{113972}Ellie!
{114111}{114139}Manny!
{114196}{114216}Ellie..
{114230}{114298}I don't want|us to be together because we have to..
{114301}{114317}I want us...
{114318}{114356}to be together because we want to!
{114358}{114416}And I wanna be with you, Ellie!
{114446}{114482}So, what do you say?
{114483}{114510}Oh, Manny..
{114510}{114543}I thought you were going to let..
{114662}{114714}You're possum enough for me!
{115063}{115098}Well, it's just you and me now...
{115099}{115134}Two bachelors..
{115134}{115178}knocking about in the wild!
{115215}{115263}Fine, but I’m not gonna carry you...!
{115263}{115298}I still have my pride, you know..
{115298}{115374}Oh, come on, buddy. For old times sake?
{115382}{115404}I’ll carry him!
{115486}{115515}But you're herd's leaving!
{115519}{115555}We are now!
{115645}{115679}Manny, who do you like better...?
{115680}{115704}Me or Diego?
{115705}{115743}Diego. Not even close!
{115751}{115795}Ha-ha! Told you!!
{115795}{115856}Manny!|You can't choose between your kids!!
{115856}{115926}He's not my kid.  He's not even my dog!
{115931}{116001}If I had a dog, and my dog had a kid..
{116002}{116039}..and the dog's kid had a pet...
{116040}{116063}that would be Sid!
{116074}{116112}- Can I have a dog, Manny?|- No..
{116121}{116162}Ellie, can I have a dog?
{116162}{116186}Of course you can, sweetie!
{116201}{116215}Ellie....
{116215}{116261}We have to be consistent with them!!
{122134}{122180}I saved you, little buddy!!
